### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by mulleydev** [bokub/linky#1]
Hello! Pour un projet pédagogique j'essaie de faire fonctionner le programme avec un compteur Linky existant, je n'arrive pas a démarrer le projet, je ne vois pas où mettre le JS qui est dans le README, et sous quel format les données sortent-elle ?

Merci d'avance ! :100:

**Comment by bokub** [comment]
Hello !
Ceci n'est pas un "programme" mais un module npm, une sorte de librairie qui s'intègre dans un projet Node.js quelconque

La librairie s’installe via la ligne de commande `npm`, puis s'importe dans votre code avec la ligne de code 
`const linky = require('@bokub/linky');`

Les données peuvent ensuite être associées à une variable (`data` dans l'exemple du README).


Si vous voulez un programme standalone, je vous conseille [linky-cli](https://github.com/bokub/linky-cli), basé sur cette librairie. Il permet entre autres de récupérer les données dans un fichier au format JSON.

**Comment by bokub** [comment]
Sinon, autre solution:

- Créez un nouveau dossier
- Installez la librairie dedans avec la commande `npm i @bokub/linky`
- Créez un nouveau fichier qui s'appelle `index.js` et  copiez-collez l'exemple du README
- Lancez le programme avec la commande `node index.js`

**Comment by mulleydev** [comment]
wow merci pour la réponse rapide ! :D
Je viens d'essayé le package avec le "runkit" sur NPM, ça a fonctionné nickel!
Quand je fait un nouveau dossier avec un index.js et avec les bons identifiants j'ai une erreur : 

/home/moi/Simplon/projets_pedago/test_recup_enedis//index.js:4
const session = await linky.login('monemail@exemple.fr', 'passWORD');
SyntaxError: await is only valid in async function

Merci beaucoup !

**Comment by mulleydev** [comment]
alors que le require renvoie bien a une fonction async :|
J'ai testé aussi la version CLI, ce n'est pas exactement ce que je cherche mais c'est du bon boulot !

**Comment by bokub** [comment]
En effet, le "await" ne fonctionne que si il est à l'intérieur d'une "async" function.

Par exemple 
```js
async function test() {
    const session = await linky.login('monemail@exemple.fr', 'passWORD');
}
```

J'ai changé le README et j'ai mis un code exemple sous forme de promesses à la place

**Comment by mulleydev** [comment]
Merci beaucoup @bokub ! :smiley:
