### ISSUE TITLE
Erreur de login sur conso.vercel.app

### ISSUE THREAD

**Issue by BlackMagik88** [bokub/linky#10]
Ca fait plaisir de voir ce genre de projet ! J'essaie depuis hier soir de m'authentifier sur [https://conso.vercel.app/](https://conso.vercel.app/) mais à chaque fois j'ai l'erreur : 

`Le serveur d'Enedis a mis trop longtemps à répondre. Rafraichissez la page (F5) pour réessayer, ou revenez plus tard.`

Vous avez une idée ?

**Comment by bokub** [comment]
Effectivement, il y a de grosses lenteurs du côté d'enedis depuis hier.

Je pense qu'il faut simplement être patient et réessayer régulièrement

Si le problème n'est pas réglé dans quelques jours, je regarderai si ça n'est pas un problème de mon côté

**Comment by BlackMagik88** [comment]
Ok, c'est bien ce que je pensais, merci pour votre réponse 😎

**Comment by bokub** [comment]
Le problème est résolu ! Il y avait effectivement une erreur de mon côté, mais le serveur d'Enedis ne répondait pas pluôt que de me répondre une erreur...

**Comment by Chocobozzz** [comment]
Bonjour,

Un grand merci pour la réécriture du module et le support. J'ai enfin pu regrapher ma conso electrique :kissing_heart:
