### ISSUE TITLE
Erreur 403 sur maxpower

### ISSUE THREAD

**Issue by Skuair** [bokub/linky#11]
Bonjour,

La commande :
`linky maxpower -s 2020-10-27 -e 2020-10-29`

me retourne toujours un 403 :
```
pi@skupi:~ $ linky maxpower -s 2020-10-27 -e 2020-10-29 
✖ Error from the Enedis API
Code: 403
Response: ""
```
Je peux bien les voir pourtant sur mon espace client. Par contre, aucun problème avec daily.

Question un peu parallèle : j'ai remarqué que si je refais un linky auth avec les mêmes credentials, les appels suivants ne marche plus à cause d'une invalidité des credentials. Je suppose que le fait de refaire un linky auth supprime les credentials actuels et il faut donc en regénérer de nouveau via conso.vercel.app.
Si je dois intégrer la lib dans un projet node.js, l'appel à la méthode Session() à chaque lancement de mon app ne risque pas de provoquer le même problème ?

Merci.

**Comment by bokub** [comment]
Salut,

Lorsque tu génères un access token et un refresh token depuis [conso.vercel.app](https://conso.vercel.app/), l'access token a une durée de vie limitée.

Lorsque l'access token arrive à expiration, le module demande un rafraichissement et récupère un nouveau access token **et** un nouveau refresh token. Ceux-ci sont stockés à la place des tokens précédents, qui ne peuvent plus du tout être utilisés

Si tu relances un `linky auth`, tu vas écraser les valeurs stockées par le module avec des tokens potentiellement invalides, ce qui va causer un 403.

Je te recommande de regénerer des tokens tous neufs, de faire un `linky auth` **une seule** fois, et normalement tout devrait fonctionner pendant 3 ans

Si c'est pas le cas, dis moi et je regarderai plus en détail

**Comment by bokub** [comment]
En effet, il y a un problème avec le scope des informations accessibles, il manque la puissance max quotidienne:

![image](https://user-images.githubusercontent.com/17952318/97576204-25adf380-19ee-11eb-8402-5b89e1b48553.png)
 J'ai fait une demande de modification à Enedis, leur temps de réactivité est assez variable, je te dirais quand c'est réglé

**Comment by bokub** [comment]
> si je refais un linky auth avec les mêmes credentials, les appels suivants ne marche plus à cause d'une invalidité des credentials

En fait, les tokens que tu génères depuis [conso.vercel.app](https://conso.vercel.app) ont une durée de vie assez courte (quelques heures). Quand ils expirent, le module demande de nouveaux tokens et remplace les anciens, de façon transparente. Cette demande de rafraîchissement invalide les anciens tokens.

Si tu relances un `linky auth` avec de vieux tokens invalides, le module ne pourra **ni** récupérer tes données, **ni** demander de nouveaux tokens, et sera donc complètement bloqué.


> Si je dois intégrer la lib dans un projet node.js, l'appel à la méthode Session() à chaque lancement de mon app ne risque pas de provoquer le même problème ?

Effectivement, il ne faut pas réutiliser les tokens de départ mais sauvegarder les nouveaux lorsqu'ils sont rafraîchis, en utilisant le callback `onTokenRefresh`

Extrait de la doc:

```js
// Créez une session
const session = new linky.Session({
    accessToken: 'access token',
    refreshToken: 'refresh token',
    usagePointId: 'usage point ID',
    onTokenRefresh: (accessToken, refreshToken) => {
        // Cette fonction sera appelée si les tokens sont rafraîchis
        // Les tokens précédents ne seront plus valides
        // Il faudra utiliser ces nouveaux tokens à la prochaine création de session
    },
});
```

**Comment by Skuair** [comment]
Merci pour ton retour et tes explications, c'est plus clair.
Je testerai le code javascript un peu plus tard.

**Comment by bokub** [comment]
Hello!

Le scope "puissance maximale quotidienne" à été ajouté par Enedis !

Je pense qu'il faudrai générer de nouveaux tokens (à vérifier), mais la commande `linky maxpower` devrait fonctionner

**Comment by Skuair** [comment]
Nickel merci. Je te fais un retour dès que j'aurais vérifié sous mon appli
également.

**Comment by Skuair** [comment]
Ca fonctionne dorénavant merci.
Juste une question avant de clôturer, est-ce qu'il faut faire une new Session avant d'appeler chaque méthode de l'API ? Car j'ai l'impression que quand mon appli fait les 2 appels getDailyConsumption et getMaxPower l'une après l'autre, j'ai une error de refresh token (401 valid crendentials mandatory...).

**Comment by bokub** [comment]
Non, la même session permet de faire autant d'appels que tu veux.

Tu es sûr que les 2 appels sont faits l'un après l'autre et pas en parallèle ? ça peut poser un problème si les tokens doivent être renouvelés

**Comment by Skuair** [comment]
Hum, effectivement, avec tous mes promise, c'est possible que ça se recouvre, j'avais pas fait attention à ça, je vais modifier.
Merci, je clôture.
