### ISSUE TITLE
error 500 when try to authenticate

### ISSUE THREAD

**Issue by piars777** [bokub/linky#12]
Hello,
When I tried to get an access token, after the authentication state, i was redirect to the callback url with this error:
`server_error lincs-internal-server-error`
`https://conso.vercel.app/api/callback?code=500&error=server_error&error_description=lincs-internal-server-error`
Did i miss something?
thank you

**Comment by bokub** [comment]
Hello 👋 

It's an error from the Enedis server. Maybe their service is down, it happens quite often.

Please wait a few hours and try again

**Comment by piars777** [comment]
Hello,
It's weird, since december 18, my app cannot get data from enedis. It's always the same error. Maybe they don't know there is a problem with the api , i'll try to contact them next week if it's not resolve.

**Comment by msj-fr** [comment]
Hello, I seem to be having the same problem : I get this error

server_error lincs-internal-server-error

and when I run a command : 
linky auth -a bt5e8GnTtMJwHkqZuNIjZbyxxxxxxxxxx -r UgIphJxxxxxxxxxxxxxxxx -u 0747xxxxxxxxxxxxxxxx
Vos tokens ont été sauvegardés avec succès

linky daily --start 2020-12-24 --end 2020-12-24
✖ Cannot refresh token
Code: 401
Response: {
    "error": "Unauthorized",
    "error_description": "Valid authentication credentials are mandatory to access the resource."
}

**Comment by msj-fr** [comment]
with the nodejs code I get this error : 
Error: Cannot refresh token

Code: 401
Response: {
    "error": "Unauthorized",
    "error_description": "Valid authentication credentials are mandatory to access the resource."
}

**Comment by bokub** [comment]
So, I just generated new tokens, ran `linky auth`, then `linky daily` a few minues ago.

Everything worked **fine**, so I have no idea what your problem is and I cannot reproduce it 🤷

Can your access your data from the Enedis website ?

**Comment by piars777** [comment]
Hello bokub,
Yes i confirm it works again since today. I re-generate my access token and it works but yesterday it didn't work. Thx

**Comment by bokub** [comment]
Great 👍
