### ISSUE TITLE
Failed to Converting circular structure to JSON

### ISSUE THREAD

**Issue by floviolleau** [bokub/linky#13]
Hi,

Thanks for your amazing project.

I have a question:

After a successfull login:
```
$ linky auth -a xxxxxxxxxxx xxxxxxxxx -r xxxxxxxxxxxxx -u xxxxxxxxxxxxxx
Vos tokens ont été sauvegardés avec succès
```

When I run daily | loadcurve | maxpower commands:
```
$ linky loadcurve --start 2021-01-01 --end 2021-01-07 --output data/conso-puissance-moyenne-2021-01-01-2021-01-05.json
```

```
✖ Converting circular structure to JSON
    --> starting at object with constructor 'TLSSocket'
    |     property '_httpMessage' -> object with constructor 'ClientRequest'
    --- property 'socket' closes the circle
```

Thanks

**Comment by floviolleau** [comment]
Sorry the problem presented above, is solved now (a problem with my DNS).

Now, I have a 500 now with loadcurve:
```
✖ Error from the Enedis API
Code: 500
Response: "Error"
```

maxpower is working fine

**Comment by bokub** [comment]
Can you see the load curve (30min step) on the Enedis website ? It may need an additional consent

**Comment by floviolleau** [comment]
On the Enedis website, I aleady approved the 2 consents.

![image](https://user-images.githubusercontent.com/5442973/104074172-b899b400-520f-11eb-8e96-2be9fa6e140c.png)


I don't see exactly where is the load curve.

Today, if I issue this cli, I have the error
```
$ linky loadcurve --start 2021-01-07 --end 2021-01-07 --output data/toto.json
✖ Invalid request: The requested period must be less than 7 days for an access to the load curve.
```

I played a bit with the dates, but always the same result.

For info, I approved the consents 7/01/2021 and created my enedis account 6/01/2021.

Edit: fixed bat copy paste of cli

**Comment by HugoPoi** [comment]
Pretty clear you need to reduce the interval to max 7 days long `The requested period must be less than 7 days for an access to the load curve`

Like `$ linky loadcurve --start 2021-01-01 --end 2021-01-07 --output data/toto.json`

**Comment by bokub** [comment]
Also, I don't understand what this `put` is supposed to do in your command..

**Comment by bokub** [comment]
Also, you should remove the space between `out` and `put`, it's supposed to be `--output` not `--out put`

**Comment by HugoPoi** [comment]
@bokub I suppose your tools depends on `https://conso.vercel.app/` being validated by Enedis first ? ( Maybe we can discuss this elsewhere )

**Comment by floviolleau** [comment]
@HugoPoi: Hi, I already reduced the interval to 1-2 days and got always the same error message. The community server is already validated by Enedis because I was able to connect both (my app on my server and Enedis through the community server).

@bokub: 👀 It is just a bad copy paste from terminal to github :)

**Comment by bokub** [comment]
Are you  sure you didn't use 2020 instead of 2021 for the `--start` argument, or something like this ? The error message comes from the Enedis server, not from my module, so I'm a little bit confused...

For example, can you try this exact command and screenshot the result ? (I tried it on my side and it works well)

```bash
linky loadcurve --start 2021-01-08 --end 2021-01-09
```

**Comment by HugoPoi** [comment]
I confirm, there is a issue on Enedis side with `loadcurve` queries.

[
![Capture d’écran du 2021-01-10 20-00-15](https://user-images.githubusercontent.com/2299861/104132583-9d998200-537e-11eb-8266-e0363f3b6205.png)
](url)

**Comment by floviolleau** [comment]
@bokub: it is working fine now for me! I think you where exact, I'm confused. I think I mismatch the year

Thanks & Sorry.
We can close the issue

PS: I started to use this tool as well, https://gitlab.com/aeneria/aeneria-app. Seems to be very interesting
