### ISSUE TITLE
lincs-internal-server-error

### ISSUE THREAD

**Issue by martindaniel4** [bokub/linky#14]
Bonjour et merci pour cette librairie tout à fait utile. 

En essayant de récupérer mes jetons d'accés via conso.vercel.app, j'obtiens l'erreur `lincs-internal-server-error` après m'être loggué sur Enedis et renseigné mon PDL à récupérer. 

Avez vous une idée de la source d'erreur? 

Merci 

![Screen Shot 2021-01-11 at 2 41 23 PM](https://user-images.githubusercontent.com/695006/104189651-41387000-541b-11eb-8a3b-77baf047e5d2.png)

**Comment by bokub** [comment]
Je viens de faire la manip et ça fonctionne bien chez moi

Peux-tu réessayer plusieurs fois à plusieurs moments de la journée ? Les serveurs d'Enedis sont souvent down... (idem que #12 )

**Comment by martindaniel4** [comment]
C'est ce qui me semblait.. merci!

**Comment by LoicTryToDev** [comment]
Bonsoir,
J'utilise ce répertoire depuis plusieurs mois sans soucis (serveurs enedis down de temps en temps en effet, mais pas de problème majeur)
Depuis plusieurs jours, les tokens ne marchent plus. En essayant d'en regénérer via conso.vercel.app (en mettant identifié sur enedis), le serveur répond "erreur 404 La page que vous recherchez n’existe pas"
(j'ai essayé plusieurs fois dans la journée et depuis 3 jours).

Enedis n'auraient-ils pas abandonné cette manière de récupérer les données ? J'ai peur qu'ils aient fait en sorte que la récupération de données ne puisse se faire uniquement depuis leur tout nouveau "https://datahub-enedis.fr/"

En vous souhaitant une bonne soirée,

Loïc

**Comment by bokub** [comment]
Salut,

Effectivement, je viens de constater le même problème de page 404...

J'essaie de regarder ça la semaine prochaine

**Comment by bokub** [comment]
Je viens de réessayer de générer de nouveaux tokens, et on dirait que le problème s'est réglé tout seul.

@LoicTryToDev Peux-tu vérifier et confirmer ?

> J'ai peur qu'ils aient fait en sorte que la récupération de données ne puisse se faire uniquement depuis leur tout nouveau "https://datahub-enedis.fr/"

Oui, c'est bien cette méthode que j'utilise, plus exactement les API "Authorize V1" et "Metering Data V4" du service "Data Connect"

**Comment by LoicTryToDev** [comment]
Bonsoir,
C'est bon ça marche à nouveau sans problème. Ton utilitaire est top, dommage que le site d'Enedis se montre indisponible par moment, après on ne peut pas leur en vouloir d'avoir des phases de maintenances (7 jours quand même ça commence à être de la bonne maintenance)
Bonne soirée, encore félicitation pour cet utilitaire
Loïc

**Comment by martindaniel4** [comment]
+1 super outil!
