### ISSUE TITLE
erreur 404 apres le login

### ISSUE THREAD

**Issue by rafipiccolo** [bokub/linky#16]
J'étais plein d'espoirs :)
mais une fois que je rentre mes identifiants ici :
https://conso.vercel.app/
je tombe sur ce message

ERREUR 404
La page que vous recherchez n’existe pas.

est-ce que c'est lié a mon compte ou bien l'api a changée et cela ne marche plus ?

**Comment by bokub** [comment]
Oui, visiblement c'est très récent (cf. #14)

Je regarde à mon retour de vacances

**Comment by bokub** [comment]
@rafipiccolo Tu peux re-tester s'il te plaît ?

**Comment by rafipiccolo** [comment]
ça marche.
gg 👍

**Comment by Giwi** [comment]
Hello, il me semble que ce soit à nouveau le cas.
