### ISSUE TITLE
Plusieurs compteurs

### ISSUE THREAD

**Issue by mnegorth** [bokub/linky#17]
Bonjour,
Merci pour ce package !
Je l'utilise pour récupérer les données de mon compteur principal mais je possède un deuxième compteur et j'aimerai savoir si il est possible de switcher de compteur sans devoir refaire un "auth" ?
J'ai un certain nombre de Rpi qui prennent la poussière et je pourrai donc  en utiliser un par compteur mais j'aimerai tout avoir sur le même.
Merci d'avance.

**Comment by bokub** [comment]
Salut !

Effectivement, je n'ai pas pensé à ce cas de figure, et pour l'instant pas possible d'avoir plusieurs configs avec le package natif.

En revanche, tu devrais pouvoir t'en sortir avec un binaire spécial qui stockerait sa config à un autre endroit.

Pour générer ce binaire, voici les instructions:

```sh
# Clone le projet
git clone https://github.com/bokub/linky.git

# Dans le fichier ./bin/store.ts, modifie les lignes 5 à 8, par exemple:
const accessTokenStoreKey = 'linky_2/accessToken';
const refreshTokenStoreKey = 'linky_2/refreshToken';
const usagePointIDStoreKey = 'linky_2/usagePointId';
const sandboxStoreKey = 'linky_2/sandbox';

# Lance les commandes suivantes pour build le binaire (il te faut Node.js installé)
npm install
npm run build
npm run pkg
```

Tu trouveras ton binaire dans le dossier `pkg`, tu peux le stocker ailleurs et supprimer le code source si tu veux.

Ensuite, pour ton compteur 1 tu fais comme tu faisais avant

Et pour le compteur 2 tu fais `./linky-linux auth` ou `./linky-linux daily`

Si tu as des questions, n'hésite pas

**Comment by mnegorth** [comment]
Super, merci pour ta réponse rapide.
J'essaie de mettre ça en œuvre et je te fait un retour.
Merci!

**Comment by mnegorth** [comment]
Désolé pour la question de néophyte mais comment faut-il faire pour avoir le package en arm (pour le Raspberry) , par défaut il crée le package en x64.
merci.

**Comment by bokub** [comment]
Ah oui, ben tu peux remplacer cette ligne:

https://github.com/bokub/linky/blob/04ddfa0e45fd3efca1a7f1c294ce78610b81c0ed/package.json#L59

par

```js
"pkg": "rm -fr ./pkg && pkg . --out-path pkg -t node12-linux-arm64",
```

Puis tu peux relancer `npm run pkg`

Si ça marche pas, tu peux aussi tenter `node12-linux-armv6` ou `node12-linux-armv7`, mais perso j'y connais rien en architectures..

La doc de pkg est [ici](https://github.com/vercel/pkg) si besoin

**Comment by mnegorth** [comment]
Je confirme qu'il faut remplacer par:
`"pkg": "rm -fr ./pkg && pkg . --out-path pkg -t node12-linux-**armv7**",`

Après qq heures (raspberry oblige) le package a bien été buildé et je peux  récupérer les infos de mes 2 compteurs.

Merci !

**Comment by bokub** [comment]
Hello @mnegorth 

Le multi-compteurs est maintenant géré depuis la version 1.5.0 ! :tada:
