### ISSUE TITLE
génération de token erreur 404

### ISSUE THREAD

**Issue by owav** [bokub/linky#18]
Hello,

À la recherche d'un utilitaire pour suivre mes données de consommations depuis mon terminal, j'ai atterri sur ce projet qui me semble tout à fait adéquat.

Malheureusement, je tombe sur une erreur 404 lors du processus de génération de token via conso.vercel.app
La redirection vers enedis se fait bien, je valide le partage des données, la callback tombe en 404 côté vercel : 

<details>
  <summary>screenshot</summary> 

 ![image](https://user-images.githubusercontent.com/1923237/122212901-a56ace80-cea8-11eb-9a70-29f51bc0e994.png)

</details>

Sinon, 👍 pour l'outil qui semble top

**Comment by bokub** [comment]
L'URL dans ton screenshot est bizarre, elle devrait plutôt ressembler à ça:

```
https://conso.vercel.app/api/callback?code=XXX&state=YYY&usage_point_id=123
```

Je viens de tester et tout a bien fonctionné. Tu veux bien réessayer ? Il n'est pas rare (c'est même très fréquent) que les serveurs d'enedis déconnent

Si ça marche pas, peux-tu me copier l'URL complète? (en changeant les données sensibles évidemment)

**Comment by owav** [comment]
En effet, ça refonctionne !

Merci pour ta réactivité et pour l'outil, bien plus pratique que l'interface bof bof d'enedis ;)
