### ISSUE TITLE
messqge d'erreur avec le module nodejs

### ISSUE THREAD

**Issue by nico53** [bokub/linky#20]
Bonjour , 
je rencontre un souci avc le module nodejs j'obtiens les messages d'erreur suivant:

```
Code: 401
Response: {
    "error": "Unauthorized",
    "error_description": "Valid authentication credentials are mandatory to access the resource."
}
    at /home/pi/js/node_modules/linky/dist/src/index.js:99:23
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:16286) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
(node:16286) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:16286) UnhandledPromiseRejectionWarning: Error: Cannot refresh token
```

En revanche cela fonctionne parfaitement avec le module cli, j'en deduis donc que les tokens sont corrects.
Avez vous une idee de l'origine du probleme?
merci
Bonne journee
Nico

**Comment by bokub** [comment]
Bonjour Nico,
Le problème apparaît il même avec des nouveaux tokens, ou bien après une trentaine de minutes ?

As-tu bien implémenté la fonction `onTokenRefresh` ?

**Comment by nico53** [comment]
Bonjour Boris, 
Il apparaît avec de suite avec nouveaux tokens. 
Nico

**Comment by bokub** [comment]
Ah c'est bizarre, t'aurais un exemple de code pour que j'essaie de mon côté ?

**Comment by nico53** [comment]
En fait je prend ton code tel que, j enregistré dans app.js et que lance par node app.js, c est peux être ça le soucis ???

**Comment by nico53** [comment]
Je pense que je n utilise pas le module correctement, il y aa un truc qui m échappé, si cela fonctionne chez toi

**Comment by bokub** [comment]
Alors, j'ai mis ce code dans un fichier `app.js`, puis j'ai lancé `node app.js`, et tout marche bien, je vois ma consommation de la semaine dernière.

```js
const linky = require('linky');

const session = new linky.Session({
    accessToken: 'Ytp2kCsTt3D******************************************************',
    refreshToken: 'thMrcY7TP*******************************',
    usagePointId: '2374*******,
});

session.getDailyConsumption('2021-06-20', '2021-06-27').then((result) => {
    console.log(result);
});
```

Si tu veux me donner plus de détails, n'hésite pas, dans le cas contraire je ne peux pas t'aider plus que ça.

Bonne journée

**Comment by nico53** [comment]
Bonjour Boris,J'ai retravaillé dessus ce matin, je pense que les tokens que j'utilisais étaient périmés avec des nouveaux cela fonctionne, reste  à voir si cela va fonctionner aurenouvellement.merci pour ta réponse
Nico

**Comment by nico53** [comment]
Bonjour Boris,
Au renouvellement des tokens, cela ne fonctionne plus, je dois comprendre comment récuperer les nouveaux tokens et les utiliser.
Bonne journée

**Comment by bokub** [comment]
Comme expliqué dans la doc, il faut que tu implémentes la fonction `onTokenRefresh`, qui sera appelée au renouvellement des tokens.

Dans cette fonction, il faut que tu stockes quelque part les nouvelles valeurs de `accessToken` et de `refreshToken`. La prochaine fois que créeras une session, il faudra utiliser ces nouveaux tokens

```js
const session = new linky.Session({
    accessToken: 'access token',
    refreshToken: 'refresh token',
    usagePointId: 'usage point ID',
    onTokenRefresh: (accessToken, refreshToken) => {
        // Cette fonction sera appelée si les tokens sont renouvelés
        // Les tokens précédents ne seront plus valides
        // Il faudra utiliser ces nouveaux tokens à la prochaine création de session
        // Si accessToken et refreshToken sont vides, cela signifie que les tokens ne peuvent plus
        // être utilisés. Il faut alors en récupérer des nouveaux sur conso.vercel.app
    },
});
```

**Comment by nico53** [comment]
Boris, 
Ou sont stocké les tokens, j esserais demain matin, merci

**Comment by bokub** [comment]
Ben j'en sais rien c'est à toi de les stocker comme tu le sens :smile: 

La librairie te permet juste de récupérer les données de consommation et de rafraîchir les tokens, mais pas de les sauvegarder, contrairement à l'outil en ligne de commande

**Comment by nico53** [comment]
Bonjour Boris,J'ai essayé cela mais sans succes la fonction onTokenRefresk me renvoie accessToken:"" et refreshToken:"".
Cela vient sans doute de mon code . Apres le refresh j'obtiens cela.auth.json{“access_token”:"",“refresh_token”:"",“usage_point_id”:“09237626592109”}linky.jsconst fs = require('fs');const util = require('util');const linky = require('linky');// Créez une sessionconst auth = require('./auth.json')const asyncWrite = util.promisify(fs.writeFile);const session = new linky.Session({ accessToken: auth.access_token , refreshToken: auth.refresh_token, usagePointId: auth.usage_point_id,  onTokenRefresh: async (accessToken, refreshToken) => {const Auth = { access_token:accessToken, refresh_token:refreshToken, usage_point_id: auth.usage_point_id }; await asyncWrite('./auth.json', JSON.stringify(Auth)); }, });session.getDailyConsumption('2020-09-01', '2020-09-08').then((result) => { console.log(result);});avant le refresh cela fonctionne parfaitement. Vois tu quelque chose de mauvais dans le code?
merci
Nico

**Comment by bokub** [comment]
Salut Nico,
Il va falloir que tu arrêtes de répondre par e-mail et que tu mettes ton code directement sur GitHub parce que là ça a retiré tous les sauts de ligne et c'est illisible :shrug:

**Comment by nico53** [comment]
Boris,Je vais lâcher l'affaire, je n'ai pas le niveau.
En tous cas merci
Nico
