### ISSUE TITLE
compte pro

### ISSUE THREAD

**Issue by fafoulon** [bokub/linky#22]
Bonjour, bravo pour le super travail!

Je l'utilise parfaitement avec un compte perso pour le compteur de la maison.
Par contre je viens de créer un compte pro sur Enedis pour associer le compte de mon local professionnel, et lorsque j'essaye de donner l'accès à l'application pour avec les Tokens, j'atterris sur la page du compte perso, où bien sur il me dit qu'aucun compteur n'est rattaché.
Comment pourrais-je faire?

**Comment by bokub** [comment]
Salut,

Pas sûr que ce soit possible.

En effet, voilà ce qu'on peut lire dans la documentation: 

![image](https://user-images.githubusercontent.com/17952318/126323559-f24ee3c9-5a9d-43e1-be91-857d8e3ae12a.png)
