### ISSUE TITLE
Demande de Token : Erreur 404

### ISSUE THREAD

**Issue by vvn0687** [bokub/linky#23]
Bonjour,

Il semblerait que l'API de demande de token pour le partage des données ait encore changé.
Je me prends une erreur 404 : 
https://conso.vercel.app/api/callback/IdPrm=XXXXXXXXXX&code=server_error&error_description=server_error&

Merci d'avance.
David

**Comment by bokub** [comment]
ça fonctionne très bien chez moi. Tu peux réessayer s'il te plaît?

Merci

**Comment by vvn0687** [comment]
Bonjour,
Effectivement, cela fonctionne maintenant.
Je me suis rendu compte hier que mon espace client enedis ne me remontait aucune conso et le statut de collecte/partage était indisponible.
C’était certainement lié à ça.
Merci !
