### ISSUE TITLE
[Auto-hébergement] Indépendance totale de la partie serveur

### ISSUE THREAD

**Issue by A-Nicoladie** [bokub/linky#24]
Bonjour,

Je tente d'installer la partie serveur avec l'ensemble des fichiers et dépendances sur mon serveur.

- Si j'ai pu récupérer les fichiers `CSS`, `JS` et les fonts qui sont appelés, je n'ai malheureusement pas accès à ce qui se passe dans `/api/collect` de ton serveur perso. Serait-il possible d'avoir cette partie ?
- Y a-t-il une config particulière à mettre pour le VHost sous Apache/Nginx ?

Merci !

**Comment by bokub** [comment]
Salut,

Juste pour être sûr, c'est quoi l'idée derrière ton projet ? Parce que je sais pas si tu réalises mais il va te falloir un `CLIENT_ID` + un `CLIENT_SECRET` fournis par Enedis. 
Et pour avoir ça, il faut créer une app accessible aux testeurs d'Enedis, qu'ils valident que ton projet marche sur un environnement de test et qu'il est conforme à leur charte, puis que tu signes un contrat qui lie Enedis et ton entreprise (si tu n'en as pas il faut en créer une 😄 ), et enfin quelques semaines plus tard tu recevras tes credentials de prod et tu pourras enfin faire tourner ton serveur.

C'est justement parce que c'est aussi compliqué que j'ai créé ce projet, dont le serveur sert **uniquement** à obtenir des tokens d'accès (aucune récupération de données de consommation, aucune BDD...).

Et pour répondre à ta question, `/api/collect` n'a aucun rapport avec ce projet, si tu regardes l'URL complète tu verras que c'est `https://metrics.boris.sh/api/collect`, et c'est tout simplement une version auto-hébergé de [umami](https://umami.is/) (des analytics qui respectent la vie privée et les données personnelles).

**Comment by A-Nicoladie** [comment]
Argh... non je n'avais pas recherché jusque là. Ça à l'air très _"simple"_ 😱😵
Je n'ai pas de projet, je suis simplement curieux. Donc bon... je ne vais pas créer une entreprise juste pour accéder à une API 😅 (et merci beaucoup d'avoir fait tout ça à notre place).

>_[...] le serveur sert uniquement à obtenir des tokens d'accès (aucune récupération de données de consommation, aucune BDD...)._

Comment savoir quelles informations transitent sur ton serveur ?  
Techniquement, tu as toutes les informations nécessaires pour interroger l'API de ton côté avec les token récupérés (je ne dis pas que c'est ce qui est fait, mais que c'est faisable), non ? 

> _[...] c'est tout simplement une version auto-hébergé de umami [...]_

Merci pour la précision, je ne connaissais pas umami (je suis plus habitué à voir passer du Piwik/Matomo ou OWA). Je vais y jeter un œil 😉

**Comment by bokub** [comment]
> Comment savoir quelles informations transitent sur ton serveur ?

Tu peux voir [dans la librairie](https://github.com/bokub/linky/blob/master/src/index.ts#L31) que tous les appels API contactent directement `enedis.fr`, sauf lorsque le token est expiré et qu'il faut [le renouveler](https://github.com/bokub/linky/blob/db69f92ff04ee17f4808d6b6807342bc3a3e933f/src/index.ts#L96-L100).

Donc quand tu fais `linky daily` par exemple, c'est directement Enedis qui répond.

> Techniquement, tu as toutes les informations nécessaires pour interroger l'API de ton côté avec les token récupérés (je ne dis pas que c'est ce qui est fait, mais que c'est faisable), non ?

Sur ce point, tu as tout à fait raison. J'ai mis tout le code du serveur [ici](https://github.com/bokub/linky/tree/master/server/api), mais effectivement, il n'y a **rien** qui prouve que c'est vraiment le code qui tourne sur le serveur, c'est juste une affirmation de ma part. Si je voulais, je pourrais tout à fait sauvegarder les tokens générés, et les utiliser pour récupérer les données de tout le monde.

Tu as donc 3 possiblités:
- Soit tu fais confiance et tu utilises `conso.vercel.app` sans vraiment savoir ce qui se passe vraiment
- Soit tu fais ton propre serveur (et dans ce cas il faut que tu crées ton entreprise et ta propre app, puis qu'Enedis la valide).
- Soit tu utilises le site d'Enedis et bye bye la CLI...


> je suis plus habitué à voir passer du Piwik/Matomo ou OWA

Effectivement, umami c'est moins courant, mais ça me permet de ne pas demander l'utilisation des cookies car aucune donnée personnelle n'est enregistrée.
Mon but est juste de compter le nombre de visiteurs pour savoir si mon outil est beaucoup utilisé et savoir si ça vaut le coup d'y passer du temps.

**Comment by A-Nicoladie** [comment]
Merci beaucoup pour toutes ces explications 😉👍

**Comment by maelgangloff** [comment]
Bonjour @bokub,
Ma question concerne le type de donnée qui est transferée sur votre serveur personnel.
En effet, en analysant les requêtes transmises, je constate que la requête POST vers votre serveur contient l'URL de la page courante et donc le paramètre `code` qui est à mon sens une information personnelle. Pourquoi ce token est-il envoyé sur votre serveur ?
![linky](https://user-images.githubusercontent.com/51171251/147880348-d443fce2-938e-451b-8936-128bf4ebe71c.png)

**Comment by bokub** [comment]
Bonjour,

Après avoir autorisé le partage des données, Enedis redirige effectivement l'utilisateur vers une page de conso.vercel.app contenant ce code.

Ce code à usage unique doit ensuite être envoyé au serveur Enedis pour être échangé contre un access token et un renew token, ce qui est effectué par mon serveur. Les tokens ainsi obtenus sont ensuite affichés sur la page.

Tu peux trouver tout ce processus quelque part dans le dossier api du repo, et plus de détails sur le mécanisme dans la documentation d'enedis.

Je t'aurais bien mis des liens directs mais je suis sur mobile et je galère un peu pour trouver

Bonne journée

**Comment by bokub** [comment]
Ah mince j'avais pas bien vu dans ton screenshot que tu parlais de la route "collect", qui correspond effectivement à mon service d'anaytics !

C'est vrai que ça pourrait être considéré comme de la donnée personnelle, il faudrait que je regarde si je peux retirer la partie query...

Hereusement, ce code est à usage unique et doit être utilisé dans les 30 secondes si je me souviens bien, donc pas super critique, mais je t'accorde que ça n'est pas idéal

**Comment by bokub** [comment]
@maelgangloff J'ai fait quelques modifications pour retirer toutes les informations "sensibles" des appels à mon service d'analytics, les changements sont déjà en production :+1:
