### ISSUE TITLE
connexion linky

### ISSUE THREAD

**Issue by hubert29** [bokub/linky#25]
ce matin je continus avec node js et cmd 
j'ai demandé des nouveaux TOKENs  car j'ai lu que ceux ci n'était valable que quelques heures avant que j'ai au moins réussi une connexion puis qu'il soit régénéré automatiquement

j'ai lancé la commande 

```
C:\Users\Acer>linky auth -ajT3tCGZG4tVC1R9daQam2JQ75SGUzegxj0M6td2ak0HCkJ05WVWCRn -r1lbBlBiVwFngWHaWfdYLQc7Ucstxd5XxzJStzDoU8QO8io -u14609551361984
```

mais j'ai eu une réponse que je ne comprends pas

`The flag --accessToken can only be set once.`

fallait-il que je demande des nouveaux Tokens ??  j'essaye de suivre l'aide en ligne

ci joint le fichier log qui je pense correspond à cette manip
[2021-12-24T09_55_17_508Z-debug-0.log](https://github.com/bokub/linky/files/7774715/2021-12-24T09_55_17_508Z-debug-0.log)

**Comment by bokub** [comment]
Bonjour Hubert,
Il faut un espace entre chaque paramètre et sa valeur.

Par exemple: `linky auth -u 146095513` et non pas `linky auth -u146095513`

Normalement, l'outil de génération de tokens te donne directement la commande pour t'authentifier

**Comment by hubert29** [comment]
merci, "les tokens ont été sauvegardés avec succès"  cela signifie : 
 1 au redémarrage de la console cmd il n'est plus nécessaire de relancer la commande "linky auth" ? il suffit alors de passer les cdes pour relevé le compteur.
2 Idem si j'utilise "linky-win.exe" au lieu de "node JS" en tenant compte "Par exemple, au lieu de faire linky --help, il faudra faire./linky-win.exe --help". Avec "linky-win.exe" cette remarque est valable pour toutes les cdes passée à la console exemple linky daily-win.exe --début 2020-09-01 --fin 2020-09-08 ?

**Comment by bokub** [comment]
C'est exactement ça, tu as tout compris

**Comment by hubert29** [comment]
salut,  je vais plus loin 
un fois que tu as récupéré les donnes de consommation par demi-heure (courbe de charge) avec la commande `linky loadcurve --start 2020-09-01 --end 2020-09-02 --output data/ma_conso.json` j'ai besoin de transférer ces données sous libre office calc. As tu  connaissance d'un outil qui ferait cela. merci

**Comment by bokub** [comment]
Quel est ton besoin ? Tu veux juste un outil pour convertir un ton JSON en tableur, ou tu veux coder un process complètement automatisé ?

**Comment by hubert29** [comment]
Pour l'instant je voudrais convertir le fichier "ma_conso.json" en CSV pour l'ouvrir en suite sur calc

**Comment by bokub** [comment]
Alors j'ai rien en particulier à te conseiller mais en cherchant "JSON to CSV" sur Google y'a des centaines d'outils qui existent, je pense que tu aurais pu trouver tout seul assez facilement...

Par exemple, premier résultat sur Google: https://www.convertcsv.com/json-to-csv.htm

Je mets ça en entrée:

```json
{
   "unit": "W",
   "data": [
      {
         "date": "2020-09-01 00:00:00",
         "value": 582
      },
      {
         "date": "2020-09-01 00:30:00",
         "value": 448
      }
   ]
}
```

Résultat CSV: 

```csv
date,value
2020-09-01 00:00:00,582
2020-09-01 00:30:00,448
```

Et ça peut même sortir un fichier Excel (que tu devrais pouvoir ouvrir avec Calc sans problème):

[output.xlsx](https://github.com/bokub/linky/files/7776086/convertcsv.xlsx)

![image](https://user-images.githubusercontent.com/17952318/147390454-c680ac92-01ab-4387-a7e5-ddd9de221e61.png)

**Comment by hubert29** [comment]
je commence vouloir extraire la courbe de charge du 2021-01-01
[extration courbe de charge.pdf](https://github.com/bokub/linky/files/7776088/extration.courbe.de.charge.pdf)
 il me réponds "'courbe' n’est pas reconnu en tant que commande interne
ou externe, un programme exécutable ou un fichier de commandes"
pourquoi?? j'ai encore du faire une connerie


![image](https://user-images.githubusercontent.com/17952318/147390891-4e99e570-c8c1-48ae-be6f-1539b1728da7.png)

**Comment by bokub** [comment]
C'est censé être quoi ces `--début` ou `courbe de charge linky` ?
Si tu inventes des commandes qui ne sont pas dans la documentation c'est normal que ça ne fonctionne pas

Juste au cas où, tu aurais pas un traducteur automatique dans activé dans ton navigateur ?

Tu est censé voir ça dans la doc:

![image](https://user-images.githubusercontent.com/17952318/147390876-17c3d3d0-4904-4837-9f7b-a0139b9c06f7.png)

**Comment by hubert29** [comment]
bonjour,
la réponse et oui et je mérite des claques!!
ce matin au premier loadcurve  j'ai eu la réponse en pièce jointe

je me demande si je dois passer la commande  npm i -g linky  chaque fois que je lance la console NodeJS ?

peux t-on avoir un autre répertoire que  c:\user\nom\data
[tokens invalide.pdf](https://github.com/bokub/linky/files/7776828/tokens.invalide.pdf)

**Comment by bokub** [comment]
Le `npm i -g linky` c'est juste pour l'installation, pas besoin de le faire à chaque fois.

Je suis pas sûr de comprendre ta question de dossier, mais tu peux utiliser cet outil depuis n'importe où

**Comment by bokub** [comment]
Pour la réponse en pièce jointe, tu dois recommencer le process d'obtention des tokens depuis le début

**Comment by hubert29** [comment]
salut as tu remarquer qu'il fonctionne par 7 jour. C'est a dire une une requête loadcurve tu ne peut pas demander plus de 7 jours.
Par rapport au jour d'aujourd'hui la requête sur les 7 jours précédents donne une donnée toutes les 30 mn en amont il y a plus qu'une donnée toutes les heures. en connais tu le motif?

**Comment by bokub** [comment]
J'ai pas compris ta question, me parles-tu de la limite de 7 jours, ou bien de l'intervalle de 30 minutes ?

Dans les deux cas, c'est un choix d'enedis, et je n'ai pas d'explication

**Comment by hubert29** [comment]
informations sur l'utilisation de l'outil m^me si cela concerne effectivement ENEDIS
au delà de 7 jours la requête loadcurve ne remonte plus les données toutes les demi heures mais uniquement toute les heures.
au changement d'heure d'hiver le dimanche 31 octobre 2021 il y a deux fois un relevé pour 02:00:00

**Comment by hubert29** [comment]
pour 2021 plus de données a remonter avant le 05/08/2021 voir la réponse à la requête pour le 01/07/2021 au 07/07/2021 en pièces jointes. La  requêtes du 01/08/2021 au 07/08/2021 n'a pas remonté de données du 01 au 04 mais ca commence au 05.
[historique limité.pdf](https://github.com/bokub/linky/files/7784208/historique.limite.pdf)
s
qu'en penses tu??

**Comment by bokub** [comment]
Le message me semble clair, Enedis n'a pas de données à te renvoyer pour cette date...
