### ISSUE TITLE
install failed sur 2 linux différents

### ISSUE THREAD

**Issue by flecoufle** [bokub/linky#28]
Hello j'ai 2 machines sur lesquelles j'ai tenté un sudo npm i -g linky

sur une machine classique 64 bits (debian like) et raspbian 9, npm 6.14.15
Les deux arrivent au même résultat : problème sur /usr/lib/node_modules/linky/dist/bin/cli.js

...
4756 silly build linky@1.4.0
4757 info linkStuff linky@1.4.0
4758 silly linkStuff linky@1.4.0 has /usr/lib/node_modules as its parent node_modules
4759 silly linkStuff linky@1.4.0 is part of a global install
4760 silly linkStuff linky@1.4.0 is installed into a global node_modules
4761 silly linkStuff linky@1.4.0 is installed into the top-level global node_modules
4762 verbose linkBins [ { linky: 'dist/bin/cli.js' }, '/usr/bin', true ]
4763 timing action:build Completed in 74ms
4764 verbose unlock done using /root/.npm/_locks/staging-a072192f34a17023.lock for /usr/lib/node_modules/.staging
4765 timing stage:rollbackFailedOptional Completed in 287ms
4766 timing stage:runTopLevelLifecycles Completed in 9658ms
4767 verbose stack Error: ENOENT: no such file or directory, chmod '/usr/lib/node_modules/linky/dist/bin/cli.js'
4768 verbose cwd /usr/lib/node_modules
4769 verbose Linux 4.19.0-18-amd64
4770 verbose argv "/usr/bin/node" "/usr/bin/npm" "i" "-g" "linky"
4771 verbose node v12.22.8
4772 verbose npm  v6.14.15
4773 error code ENOENT
4774 error syscall chmod
4775 error path /usr/lib/node_modules/linky/dist/bin/cli.js
4776 error errno -2
4777 error enoent ENOENT: no such file or directory, chmod '/usr/lib/node_modules/linky/dist/bin/cli.js'
4778 error enoent This is related to npm not being able to find a file.
4779 verbose exit [ -2, true ]

une idée ?

**Comment by bokub** [comment]
C'est peut être la mise à jour d'hier qui est foireuse..

Tu peux essayer un `sudo npm i -g linky@1.3.0` et me dire si ça fonctionne ?

**Comment by bokub** [comment]
Hello,

C'est la version 1.4.0 que j'ai sorti hier qui déconne, je viens de la retirer de npm

Un fix est en cours, et en attendant, tu peux simplement faire `sudo npm i -g linky@1.3.0`

**Comment by flecoufle** [comment]
c'est ca, la version précédente s'installe correctement, merci
la version 1.4.1 est :ok_hand:

**Comment by bokub** [comment]
Parfait, j'allais justement te dire que le problème était réglé

Bonne journée ! :+1:
