### ISSUE TITLE
Fonctionnement HS d'Enedis sur Chrome, il faut passer par firefox

### ISSUE THREAD

**Issue by arnaudtora** [bokub/linky#29]
Sur Chrome, j'ai des problèmes sur le site d'Enedis (erreur serveur).
En tentant de récupérer mes tokens, je tombe sur une page 404.

En lisant sur le net, j'ai vu que le site Enedis ne fonctionnerait pas trop sur Chrome.

J'ai tenté de passer par Firefox -> Le site Enedis fonctionne mieux et tout fonctionne, j'ai mes tokens.

Merci pour le travail !

**Comment by JocelynPa** [comment]
Bonjour, 

Pour moi impossible d'obtenir mes tokens, je reçois bien un mail m'informant que je partage mes données mais je n'obtiens aucun token 

Qui peut me donnée un coup de main?

**Comment by bokub** [comment]
@JocelynPa Pas la peine de spammer sur plusieurs issues, c'est #36 que tu cherches

**Comment by JocelynPa** [comment]
@bokub 
Oui désolé j'ai oublié de supprimer sur cet issues après avoir posté sur l'autre. 
Merci pour le retour
