### ISSUE TITLE
Erreurs lors des premiers essais

### ISSUE THREAD

**Issue by arkhaiel** [bokub/linky#30]
Hello ! Très enthousiaste quant à ce projet, je viens d'installer le package et essayer de l'utiliser de façon simple, j'ai des erreurs malgré la confirmation de Enedis et de la commande `auth`. 
Une idée ? 

![image](https://user-images.githubusercontent.com/65437872/154869467-6e4128a1-0b11-4652-a284-cd5807568874.jpeg)

Merci !

**Comment by arkhaiel** [comment]
My bad, je crois que j'ai été trop impatient (ou que les serveurs Enedis étaient down ?). 
Ça fonctionne à merveille.
Merci beaucoup pour ton travail, je m'étais renseigné sur les démarches pour pouvoir obtenir ces données et ce que tu as réalisé est très utile !!

PS : savons-nous la fréquence de mise à disposition des données ? Est-ce une fois par jour ?

**Comment by bokub** [comment]
Il faut savoir que les serveurs d'Enedis sont souvent down, et que tout est souvent cassé chez eux (en plus d'être compliqué).

Bref, ravi que mon projet te soit utile !

**Comment by bokub** [comment]
Pour la fréquence des données, oui c'est bien une fois par jour. En gros à partir de minuit passé (peut-être un peu après) tu peux consulter les données de la veille.
