### ISSUE TITLE
merci de ce taf

### ISSUE THREAD

**Issue by dltrainou** [bokub/linky#31]
ça fonctionne impec, merci.
y aurait il une possibilité de faire une sortie "csv" ou "xls" en plus du json?
merci d'avance
bonne journée

**Comment by bokub** [comment]
Avec plaisir!

Non je ne vais pas gérer tous les formats de sortie possible, libre à toi de convertir le JSON automatiquement au format de ton choix, par exemple avec ça: https://github.com/zemirco/json2csv

**Comment by dltrainou** [comment]
Ok merci , c’est pas grave. J’engrange l’historique en excel et je n’arrive pas a importer  la sortie json !!
Sinon, je vais la décortiquer moi-même.
Merci encore et bonne journée
