### ISSUE TITLE
Converting circular structure to JSON

### ISSUE THREAD

**Issue by garnierph** [bokub/linky#32]
Bonjour,

Tout d'abord, un grand merci pour ton travail! Quand le site d'Enedis fonctionne, c'est que du bonheur!
Depuis ce matin, j'ai le message suivant quelle que soit la commande  "linky daily", "linky loadcurve" ou "linky maxpower":
✖ Converting circular structure to JSON
J'ai renouvellé (au cas où) les deux tokens "from scratch" depuis https://conso.vercel.app/ mais rien n'y fait. :-(
J'ai également constaté que le site d'Enedis était "down" ce week-end (maintenance, upgrade...?)

L'erreur ci-dessus est beaucoup reprise dans le web (de manière générale) mais difficile pour moi de comprendre le problème!

Merci

**Comment by bokub** [comment]
Salut, 

Ce genre d'erreur arrive généralement quand un programme essaie d'afficher une erreur au format JSON mais que le format de l'erreur ne le permet pas.

En gros, Enedis renvoie une erreur, mon programme essaie de l'afficher dans la console, et puis ça plante. 

Comme pour 95% des problèmes de linky, mon conseil est d'attendre et de réessayer demain 🤷🏻‍♂️

**Comment by garnierph** [comment]
Merci beaucoup pour ton explication!
C'est quand même bien dommage que le backend ne soit pas plus stable! Je travaille sur pas mal d'APIs pour ma domotique et heureusement, la stabilité est au rendez-vous pour la plupart des devices que je gère.
