### ISSUE TITLE
Consommation de la veille

### ISSUE THREAD

**Issue by terry3772** [bokub/linky#34]
Bonjour,

Supposons que nous soyons le 19.05.2022 et que l'on veuille récupérer les consommations journalières jusqu'à la veille.

1) Essayons cela :
getDailyConsumption( 2022-05-15 , 2022-05-19 )
Error: Invalid request: The end date parameter must be earlier than the current date.
=> La borne de fin ne peut être la date du jour, admettons...

2) Et ceci :
getDailyConsumption( 2022-05-15 , 2022-05-18 )
{
  unit: 'Wh',
  data: [
    { date: '2022-05-15', value: 8162 },
    { date: '2022-05-16', value: 7335 },
    { date: '2022-05-17', value: 3674 }
  ]
}
=> Ca fonctionne, mais de fait la consommation de la veille n'est pas incluse puisque la borne supérieur est exclue.

Ca signifie que l'on ne peut pas récupérer la consommation de la veille ?

**Comment by bokub** [comment]
Bonjour Thierry, 

Effectivement, c'est ici le meilleur endroit pour poser des questions sur cet outil :wink: 

La première chose à savoir c'est que toutes les erreurs que tu vois viennent de l'API Enedis, mon outil ne sert que d'intermédiaire pour l'appeler. Or, le système d'Enedis est rempli de bugs et d'incohérences en tout genre.

C'est un peu bizarre que tu aies reçu "The end date parameter must be earlier than the current date", parce que je viens de tester ce matin et cela fonctionne bien avec une date de fin au 19 mai.

Peut-être que tu as fait la requête trop tôt dans la journée, je sais pas à quelle heure Enedis considère qu'on est "le lendemain" mais je suis près à parier que ça n'est pas à minuit pile.

Est-ce que tu peux réessayer maintenant qu'il est un peu plus tard ?

**Comment by terry3772** [comment]
Bonjour Boris,

Je confirme, tu cernes bien  la logique hasardeuse de l'API et tu as vu juste !
Nouvel essai à 14h00 :
getDailyConsumption( 2022-05-17 , 2022-05-19 )
{
  unit: 'Wh',
  data: [
    { date: '2022-05-17', value: 3674 },
    { date: '2022-05-18', value: 4065 }
  ]
}

Il n'est pas choquant que les données ne soient pas disponibles au petit matin...
Cependant le message "The end date parameter must be earlier than the current date" n'est pas adapté.
Il aurait été plus juste de renvoyer "Data not yet available".

Mais de toute façon, de manière général, il ne me semble pas judicieux que l'API se focalise sur les dates.
Problème si date de début < 3 ans (pas d'historique) => ERREUR
Problème si date de de fin > date du jour => ERREUR
etc.
Je pense que considérant une plage de dates valide (date1 <= date2), il suffirait de renvoyer les données disponibles.
Exemples :
getDailyConsumption( 2000-01-01 , 2030-05-19 ) renverrait les données sur 3 ans
getDailyConsumption( 2022-01-01 , 2030-05-19 ) renverrait les données depuis le début de l'année
etc.
On se poserait moins de question en amont dans notre programmation en réduisant ainsi la complexité même de l’algorithme.
Dans la cas présent, on doit savoir que les données sont historisées sur 3  ans, savoir à quel moment récupérer les données de la veille...
Que de questions inutiles !
La logique métier n'est pas au bon endroit et de fait si elle change côté Enedis, cela impactera le programme côté client, qui devra être modifié.

Mais tout ça est de la responsabilité d'Enedis.

Amicalement.

**Comment by bokub** [comment]
C'est vrai que je ne me suis jamais posé toutes ces questions sur de grandes plages de dates :shrug: 

L'usage type que j'imagine de mon module, c'est quelqu'un qui lancerait un script tous les matins à 6h00 pour récupérer les données de la veille et les ajouter à une BDD ou à un historique par exemple, mais j'imagine qu'il y a plein d'autres usages possibles !

Content d'avoir pu régler ton problème :+1:
