### ISSUE TITLE
Token irrécupérable (bloqué sur la page de consentement)

### ISSUE THREAD

**Issue by inoxas78** [bokub/linky#36]
Hello, 

Tout d'abord merci pour ton travail et ce que tu permets de faire en domotique.

Je ne sais pas si c'est moi ou Enedis ou autre mais le token semble irrécupérable, la page reste sur l'écran de validation, tu cliques, tu attends et rien, néanmoins je reçois bien le mail de partage de mes données av Bokub Linky.
J'ai essayé sous chrome, firefox et meme internet explorer avec le logo en bleu....

En inspectant la page je tombe sur ça comme erreur si ça peut aider à trouver une réponse: `Uncaught SyntaxError: unexpected token: numeric literal`

**Comment by bokub** [comment]
Hello,

C'est probablement Enedis qui fait des caprices.

Peux tu réessayer après 24h voire plus ? Ce genre de problème se résout souvent tout seul en quelques jours

Si ça reste cassé j'y jeterai un coup d'œil

**Comment by inoxas78** [comment]
Ok je reste patient et je re-test :)

**Comment by inoxas78** [comment]
@bokub je pense que Enedis a changé qqch, voici ce que remonte le site:
'"messageError":null,"nomTiers":"Bokub Linky","redirectUri":"https://conso.vercel.app/api/callback","status":0'
et on voit aussi 
`Le cookie « ADRUM_BTa » a été rejeté car il a déjà expiré. [e882c1ea-add0-4d9b-ac79-96513c88bfbe](https://apps.lincs.enedis.fr/mes-consentements/api/private/v1/personnes/TIG931AKR/tiers/e882c1ea-add0-4d9b-ac79-96513c88bfbe)
Le cookie « ADRUM_BT1 » a été rejeté car il a déjà expiré. [e882c1ea-add0-4d9b-ac79-96513c88bfbe](https://apps.lincs.enedis.fr/mes-consentements/api/private/v1/personnes/TIG931AKR/tiers/e882c1ea-add0-4d9b-ac79-96513c88bfbe)
Le cookie « ADRUM_BTs » a été rejeté car il a déjà expiré. [e882c1ea-add0-4d9b-ac79-96513c88bfbe](https://apps.lincs.enedis.fr/mes-consentements/api/private/v1/personnes/TIG931AKR/tiers/e882c1ea-add0-4d9b-ac79-96513c88bfbe)
Le cookie « ADRUM_BTa » a été rejeté car il a déjà expiré. [e882c1ea-add0-4d9b-ac79-96513c88bfbe](https://apps.lincs.enedis.fr/mes-consentements/api/private/v1/personnes/TIG931AKR/tiers/e882c1ea-add0-4d9b-ac79-96513c88bfbe)
Le cookie « ADRUM_BT1 » a été rejeté car il a déjà expiré. [e882c1ea-add0-4d9b-ac79-96513c88bfbe](https://apps.lincs.enedis.fr/mes-consentements/api/private/v1/personnes/TIG931AKR/tiers/e882c1ea-add0-4d9b-ac79-96513c88bfbe)
Le cookie « ADRUM_BTs » a été rejeté car il a déjà expiré. [e882c1ea-add0-4d9b-ac79-96513c88bfbe](https://apps.lincs.enedis.fr/mes-consentements/api/private/v1/personnes/TIG931AKR/tiers/e882c1ea-add0-4d9b-ac79-96513c88bfbe)`

**Comment by bokub** [comment]
Tu la vois où cette erreur exactement ?

C'est possible d'avoir une capture d'écran stp ? 

Je ne peux pas tester de mon côté car aucun ordinateur à disposition pendant quelques semaines

**Comment by inoxas78** [comment]
En faisant une inspection de la page et en cliquant sur e882c1ea-add0-4d9b-ac79-96513c88bfbe dans l'inspecteur.
Je fais l'inspection de la page où on valide pour avoir le callback.

**Comment by bokub** [comment]
Je viens de recevoir ça par mail, Enedis vient de se rendre compte que leur outil est cassé depuis le 31 mai.. 🤦‍♂️

![Screenshot_20220603_183830_com.google.android.gm.png](https://user-images.githubusercontent.com/17952318/171838820-0e953588-1f8e-4b2f-92db-57c4d609085e.png)

Il va falloir s'armer d'un peu de patience supplémentaire !

**Comment by inoxas78** [comment]
Ah bah voila :) j'étais pas si naze du coup ça me rassure :)
Merci pour ton implication

**Comment by inoxas78** [comment]
Hello @bokub 
Pour te signaler que Enedis renvoie une 404 maintenant quand tu essaies de récupérer le token.
Bien à toi.

**Comment by bokub** [comment]
Ah, ben moi j'arrive même pas à passer l'étape de consentement, le bouton valider ne fonctionne pas :face_exhaling: 

Edit: Le bouton fonctionne vue que je reçois un e-mail, mais je reste sur la page de consentement au lieu d'être redirigé !

Visiblement je ne suis pas le seul à avoir ce problème: https://github.com/saniho/apiEnedis/issues/182

![image](https://user-images.githubusercontent.com/17952318/174032465-6b1ae1f9-9bbc-47e3-8514-9d857188f7e8.png)

**Comment by JohanSweck** [comment]
hello.

Même probleme ici aussi. Tout ce passait bien jusqu'au moment ou la renouvellement auto du tokenn'a pas pu se faire et maintenant je suis bloqué sur cette page de consentement.

**Comment by Li0nc0** [comment]
Bonjour,

Encore merci @bokub pour tout ton travail.
Renouvellement impossible de mon côté également, coincé au même endroit (j'ai même tenté avec un vieil IE sur une VM Windows XP, c'est dire la détresse).
Merci à @inoxas78 pour l'alerte.
Je réessayerai régulièrement et reposterai ici si ce n'est déjà fait par un autre. :)

**Comment by Sylv63** [comment]
Hello,
J'ai le même problème (j'ai click comme un fou sur le bouton validé, j'ai reçu beaucoup de mails :D )
Idem je vous tiens au courant si ça marche un jour :)

**Comment by bokub** [comment]
Pour info je viens de recevoir ça par email à l'instant

![Screenshot_20220624_124720_com.google.android.gm.png](https://user-images.githubusercontent.com/17952318/175519867-464c47ca-f42c-4499-95dd-e23ad7e0410f.png)

**Comment by MarcAurel** [comment]
Je confirme, ça fonctionne à nouveau correctement de mon coté.

**Comment by inoxas78** [comment]
Je confirme aussi que tout remarche :)

**Comment by bokub** [comment]
Excellente nouvelle ! 

(et merci Enedis d'avoir corrigé en seulement 25 jours c'est vraiment une belle perf :smile: )

**Comment by JohanSweck** [comment]
merci pour l'info. Ca marche bien.
