### ISSUE TITLE
Ajout d'une option quiet (-q) pour supprimer l'affichage par defaut. (faciliter l'utilisation des scripts)

### ISSUE THREAD

**Issue by sdalu** [bokub/linky#37]
Pour facilement scripter l'utilisation de "linky" il est necessaire de pouvoir supprimer l'affichage standard et de le remplacer par le json.

Par exemple l'ajout d'une option -q (quiet) supprimant l'affichage par defaut permettrait une utilisation
~~~
npx linky -q -o /dev/stdout | jq ...
~~~

**Comment by bokub** [comment]
Hello, super idée !

Tu veux faire une Pull Request ?

**Comment by sdalu** [comment]
JavaScript c'est pas trop mon truc, il vaut mieux que ca ne soit pas moi

**Comment by bokub** [comment]
@sdalu à partir de la version 1.6.0, tu peux utiliser le flag `--format` pour sortir du JSON, et `--quiet` pour masquer les logs et animations.

Par exemple, pour afficher la valeur de la consommation de la veille:

```sh
npx linky daily -q -f json | jq ".data[0].value"
```
