### ISSUE TITLE
Erreur durant la conversion du JSON

### ISSUE THREAD

**Issue by sdalu** [bokub/linky#38]
De facon assez recurante l'erreur suivante se produit
~~~
✖ Converting circular structure to JSON
    --> starting at object with constructor 'TLSSocket'
    |     property '_httpMessage' -> object with constructor 'ClientRequest'
    --- property 'socket' closes the circle
~~~

**Comment by bokub** [comment]
Salut,

Alors cette erreur ça vient d'une erreur de requête, typiquement une erreur réseau.

Le code essaie de logger l'erreur au format JSON mais bon c'est un objet avec des références à lui-même donc ça échoue

Il faudrait trouver où est ce code et changer la façon dont l'erreur est loggée

**Comment by sdalu** [comment]
Si il y a moyen d'activer des options de debug, je peux poster les traces

**Comment by sdalu** [comment]
A noter que cela semble se produire la premiere fois que "linky" n'a pas été exécuté depuis un "certain temps" (moins de 30 min)

**Comment by bokub** [comment]
Hello @sdalu 

La version 2 du module étant sortie la semaine dernière, je me permets de fermer cette issue. N'hésite pas à en ouvrir une nouvelle si tu constates le même problème

Bonne journée !
