### ISSUE TITLE
Génération de tokens impossible

### ISSUE THREAD

**Issue by websilone** [bokub/linky#43]
Bonjour,

depuis l'app conso.vercel.app, quand je clique sur le bouton pour accéder à mon espace client Enedis, je tombe sur une 404 (https://mon-compte-particulier.enedis.fr/dataconnect/v1/oauth2/authorize avec des query params ensuite)
Je ne trouve nulle part comment générer les tokens pour autoriser l'accès à l'app.

Merci.

**Comment by bokub** [comment]
Hello,

Ouais effectivement j'ai le même souci. C'est possible que le service d'Enedis soit down (c'est **très** fréquent).

Je t'invite à réessayer tous les jours, si en fin de semaine c'est pas résolu dis le moi et je leur enverrai un e-mail

**Comment by websilone** [comment]
Ok, merci pour ton retour rapide. 

Je réessayerai dans la semaine. 

(Fun fact: je m'appelle Boris aussi 😉)

**Comment by BDEM-Inetum** [comment]
Hello même problème,
par contre avec ce plugin home assitant [https://github.com/saniho/apiEnedis](https://github.com/saniho/apiEnedis) j'ai bien des données qui remontent.

**Comment by mwahamwa** [comment]
Hello même problème,
par contre avec ce plugin home assistant [https://github.com/saniho/apiEnedis](https://github.com/saniho/apiEnedis) j'ai bien des données qui remontent.

**Comment by bokub** [comment]
@elbenzi OK mais est-ce que tu arrives à générer de nouveaux tokens sur enedisgateway.tech ? (la passerelle utilisée par ton plugin)

Perso je vois moi aussi la page 404

**Comment by mwahamwa** [comment]
En effet, idem via l'autre "plateforme" https://myelectricaldata.fr/
Donc "ça bouge" chez enedis...

**Comment by bokub** [comment]
Connaissant les bougres, c'est pas impossible qu'ils aient cassé leur plateforme sans faire exprès et qu'il ne s'en soient pas encore rendu compte (comme on a pu le voir dans #36)...

![image](https://user-images.githubusercontent.com/17952318/214800473-e5d20f6c-f266-4f21-92f3-36ca601985dd.png)

Je leur envoie un e-mail demain si c'est pas réglé, promis !

**Comment by Jojo75** [comment]
27/1 problème toujours présent.
En plus pygazpar buggue également par ajout d'un capchka sur la page de login !
Donc plus de consommation énergétique !!!!

**Comment by BDEM-Inetum** [comment]
Cette page semble hs erreur 500 :
https://apps.lincs.enedis.fr/mes-consentements/api/private/v1/personnes/DR19NBO/tiers/XXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXX = client_id

**Comment by nicolasvnr** [comment]
Bonjour,
En effet, je suis également développeur, et j'ai récemment ouvert un contrat chez eux pour l'API v4. Au moment de la mise en prod, ils m'ont dit que la v5 était sortie et qu'elle serait obligatoire fin avril. J'ai donc entrepris de tout jeter le dév que je venais de faire pour me mettre sur la v5. Depuis décembre, elle n'a jamais été en état de marche... donc difficile de préparer pour mise en prod.
Bon courage

**Comment by websilone** [comment]
Ca y est, ils se sont réveillés ;-) (email reçu ce matin)

<img width="602" alt="Capture d’écran 2023-01-31 à 10 22 20" src="https://user-images.githubusercontent.com/1183094/215719967-4cd79e32-d5da-4697-a889-86b70228ccab.png">

**Comment by bokub** [comment]
"Indisponible depuis le 27/01" mais cette issue date du 24/01 :smile:

**Comment by phis5533** [comment]
Là on a carrément un 404 !

![image](https://user-images.githubusercontent.com/37141288/216140759-5529c129-7908-467c-bc91-b9be7f7a3a8c.jpeg)

**Comment by Septain21** [comment]
Bonjour

J'ai peur qu'ils attendent la V3, quel intérêt de travailler sur un truc qui doit mourir demain. A part, le service qu'ils doivent à leur client ou pas....

**Comment by phis5533** [comment]
Bonjour, savez vous combien de temps ils mettent pour réparer chez Enedis habituellement ?
Merci

**Comment by nicolasvnr** [comment]
Bonjour,
Sur la nouvelle version de l'API à mon avis ça a l'air d'être encore en alpha, donc j'aurais envie de dire d'ici à ce que la v4 soit deprecated ça marchera peut-être 😆

**Comment by Septain21** [comment]
Bonjour

Pourquoi vanter le Linky pour son côté suivi des consommations si en fait on peut pas le faire. D’autres intérêts qu’on connaîtra plus tard ?

**Comment by bokub** [comment]
Je pense qu'ils mettent tous leurs efforts sur [leur propre plateforme](https://mon-compte-client.enedis.fr/) et pas du tout sur leur API qu'ils considèrent comme secondaire car utilisée uniquement par des "tiers" :shrug: 

Dans tous les cas c'est pas un problème nouveau et on peut difficilement faire autrement que de rester patient et leur remonter les problèmes au fur et à mesure...

**Comment by sdalu** [comment]
Pour info, pour ceux qui peuvent migrer vers une solution zigbee,  il y a moyen de recuperer la consommation actuelle à la minute grace à: https://lixee.fr/produits/37-zigate-usb-ttl-3770014375148.html
La qualité de service est bien meilleure que ce que fourni enedis :laughing:

**Comment by iamnague** [comment]
Cela fait maintenant 1 mois que l'API Authorize est down. 
Et depuis jeudi dernier, Enedis renvoie une erreur 500 pour l'un de mes compteurs (1 sur 4, les 3 autres sont encore ok). Je ne sais pas quoi faire.

**Comment by nicolasvnr** [comment]
> Je ne sais pas quoi faire.

Malheureusement rien, la balle est dans le camp d'Enedis :/

**Comment by iamnague** [comment]
Ce matin, l'erreur 404 n'est plus présente, il est à nouveau possible de générer des tokens.

**Comment by bokub** [comment]
Je confirme, tout fonctionne correctement, problème réglé en moins d'un mois :muscle: 
 
Même Enedis n'est pas au courant :

![image](https://user-images.githubusercontent.com/17952318/220293360-19c95dbd-5960-4369-89f3-6d726a5ecf69.png)

**Comment by sdalu** [comment]
Peut etre trop optimiste...
~~~
L'appel à Enedis a échoué...
Erreur: server_error
Description: server_error
~~~

**Comment by bokub** [comment]
Effectivement, ça n'a pas fonctionné longtemps.

Même leur propre plateforme est down là

![image](https://user-images.githubusercontent.com/17952318/220315084-c7fafd4c-0160-477f-b30d-f8df4d370959.png)

**Comment by Pat5488** [comment]
bonjour, cela fonctionne correctement pour moi, test à l'instant.

**Comment by bokub** [comment]
Bonjour à tous,

Le problème est maintenant officiellement résolu chez Enedis, je ferme donc cette issue

Bonne journée

![image](https://user-images.githubusercontent.com/17952318/220595300-c2b7425a-6dd4-4fa4-8a93-15ea665a7c0d.png)
