### ISSUE TITLE
Token non renouvelé pour second compteur Linky

### ISSUE THREAD

**Issue by DaeroValoti** [bokub/linky#44]
Hello, 

Déjà merci pour le boulot et la clarté des explications.
J'ai deux compteur linky et je compte requêter les données pour les deux.
Je m'enregistre sur le site pour avoir mon token + resfesh et exécute une seule fois le "linky auth" pour les deux compteurs avec le -u XXX.

Seul le token pour le premier compteur est rafraichi (fréquence daily) lorsque je fais un fitbit daily !

***
1er compteur
✔ Récupération de la consommation quotidienne
✔ Vos tokens ont été automatiquement renouvelés
✔ Résultats sauvegardés dans data/ma_conso_P7N_daily.json

2nd compteur
✖ Impossible de rafraichir vos tokens...
Veuillez réessayer plus tard ou relancez 'linky auth' avec de nouveaux tokens
***

Une idée de ce qu'il peut se passer ?

**Comment by bokub** [comment]
Hello ! :wave: 

1. C'est quoi `fitbit` ? Et `dailyconso` ?
2. Il faut que tu fasses `linky daily -u xxx` pour chacun de tes compteurs, si tu ne précises pas de `-u` ça utilise par défaut le dernier que tu as utilisé, je te renvoie à cette partie du README:

> Pour gérer plusieurs compteurs (PRM), précisez simplement l'usage point ID dans chaque commande avec le paramètre `-u`
> 
> ```
> # Enregistre les identifiants du compteur 111222333
> linky auth -a Tk42pB -r 8peqHT -u 111222333
> 
> # Enregistre les identifiants du compteur 777888999
> linky auth -a 9urfYR -r 5wcCPq -u 777888999
> 
> # Récupère la consommation du compteur 111222333
> linky daily -u 111222333
> 
> # Récupère la production du compteur 777888999
> linky dailyprod -u 777888999
> ```

**Comment by DaeroValoti** [comment]
J'ai corrigé mon post, par "linky" et "daily".

Je fais bien les deux appels distincts : 
- linky daily -u xxx --output ....json
- linky daily -u yyy --output ....json

J'ai bien suivi le script et mes tokens ont bien été enregistrés après les deux "linky auth"

**Comment by bokub** [comment]
OK, visiblement les tokens du deuxième compteur ne sont plus valides...

Tu peux régénérer des tokens pour le deuxième compteur ?

Ensuite tu fais un `linky auth` mais tu supprimes quelques caractères de ton `access_token` (`-a`), pour forcer le rafraîchissement.

Ensuite tu fais un `linky daily` sur chacun de tes compteurs.

Le problème est-il toujours là ?

**Comment by DaeroValoti** [comment]
Alors çà fonctionne pour le moment. Je teste dans quelques heures pour vérifier le refresh.
Peut-être qu'il faut demander la génération de token compteur par compteur sur la page Enedis ...

**Comment by bokub** [comment]
Ah mais j'avais pas compris, tu utilisais le même jeu de tokens pour les deux compteurs ? (je n'ai qu'un seul compteur donc je n'ai jamais pu tester ou voir comment ça fonctionne)

Effectivement il te faut un jeu distinct pour chacun des compteurs, si Enedis le permet

**Comment by DaeroValoti** [comment]
Oui ENEDIS permet de sélectionner les points de livraison concernés par le partage, on peut donc en mettre plusieurs pour la génération de token unique.
Je viens donc de demander la génération d'un token que pour le second, et çà devrait donc contourner le problème !
