### ISSUE TITLE
"no measure found for this usage point" avec loadcurvprod

### ISSUE THREAD

**Issue by Li0nc0** [bokub/linky#46]
Bonjour Bokub,

Je préfère ouvrir une nouvelle issue plutôt que d'alimenter la précédente #45 

Depuis le 21 janvier 2023, lorsque nous essayons de récupérer les valeurs via loadcurveprod, nous obtenons le message ci-dessous.
Nous avons bien activé la collecte de la production horaire.
Aucun soucis avec loadcurve, c'est uniquement loadcurveprod qui nous remonte ce message quelque soit le jour choisi depuis le 21/01/23.
Et cela fonctionnait bien avant.

Je ne sais pas si Enedis a changé quelque chose sur la collecte de production uniquement. :(

```
✖ Error from the Enedis API
Code: 404
Response: {
    "error": "no_data_found",
    "error_description": "no measure found for this usage point",
    "error_uri": "https://bluecoder.enedis.fr/api-doc/consulter-souscrire"
}
```

Merci pour le programme ;)

**Comment by bokub** [comment]
Hello,
Tu es sûr que tu utilises le bon usage point ?

Je ne produis pas d'électricité moi même mais j'ai cru comprendre qu'il y avait un usage point id distinct pour la consommation et la production

**Comment by Li0nc0** [comment]
Hello, je confirme que je n'ai qu'un seul point de livraison.
Et la fonction dailyprod fonctionne parfaitement quant à elle avant et après le 21 janvier jusqu'à maintenant.
Surement un soucis côté Enedis ^^

**Comment by bokub** [comment]
Hello @Li0nc0 ,

Je t'invite à réessayer avec la version 2 du module, et à ré-ouvrir une issue si tu as toujours un problème.

Bonne journée !
