### ISSUE TITLE
Executer "linky" dans un crontab  

### ISSUE THREAD

**Issue by steflp** [bokub/linky#47]
Bonjour, 
impossible d'exécuter le programme dans un cron  
Erreur  :  
`✖ Error from the Enedis API
Code: 500
Response: {
    "error": "Internal Server error",
    "error_description": "Un problème a été rencontré lors du traitement.",
    "error_uri": "https://bluecoder.enedis.fr/api-doc/consulter-souscrire"
}
`
Vraiment pas possible  ?

**Comment by bokub** [comment]
Bonjour,
Je pense plutôt que Enedis est down, c'est très fréquent surtout en ce moment

**Comment by steflp** [comment]
sincèrement je ne pense pas  car lorsque je l'utilise en  ligne de commande : c'est  OK  
je teste dans le cron a  12:10  NOK et de suite en ligne de commande : OK ,
Peut etre uniquement parce qu'il est utilisé dans un cron ?

**Comment by steflp** [comment]
autant  pour  moi  .... ca vient de passer  ...

**Comment by bokub** [comment]
Dans cas tu as peut-être raison, mais normalement il n'y devrait pas y avoir de problème avec un cron.

Peux tu partager la commande exacte que tu lances dans ton cron ?

**Comment by steflp** [comment]
C'est un script que j'exécute a  00:05

#!/bin/bash
hier=`date --date '1 days ago' +"%Y%m%d"`
hier2=`date --date '1 days ago' +"%Y-%m-%d"`
jour=`date --date 'now' +"%Y%m%d"`
jour2=`date --date 'now' +"%Y-%m-%d"`

linky loadcurve --format json --quiet --output /var/log/linky/conso_jour_$hier.json
linky daily --format json --quiet --start $hier2 --end $jour2 --output /var/log/linky/conso_totale_jour_$hier.json

**Comment by Li0nc0** [comment]
Hello,

Pour avoir déjà eu le cas, j'ai décalé l'exécution du script à 6h00 du matin au lieu d'environ minuit.
Peut être que les données ne sont pas immédiatement dispo près minuit...

**Comment by bokub** [comment]
En effet, les donnés d'une journée sont envoyées par ton compteur pendant la nuit, puis ces données sont traitées et stockées par Enedis, et deviennent disponibles tôt le matin (en général entre 6h et 8h)

**Comment by steflp** [comment]
Bonjour , cette nuit n'est pas passée  ..
Je décale pour demain a  06h05 
je fermerai la demande..
Merci pour les retours

**Comment by steflp** [comment]
ce matin , OK  
je ferme la demande
