### ISSUE TITLE
Utilisation du refresh token

### ISSUE THREAD

**Issue by KostadinovicNikola** [bokub/linky#48]
Bonjour, j'aimerai savoir comment faire pour utiliser le refresh token et avoir un nouveau acces token en ligne de commande.
J'utilise linky-win.exe sur notebook et j'aimerais pouvoir faire en sorte de lancé la commande pour avoir les données de consommation toutes les 30min.

**Comment by bokub** [comment]
Bonjour,
Quand tu récupères ta consommation en ligne de commande, si Enedis renvoie une erreur d'authentification, le refresh token est **automatiquement** utilisé pour obtenir une nouvelle paire de tokens, qui sont alors sauvegardés sur ton ordinateur.

Exemple de renouvellement automatique:

![image](https://user-images.githubusercontent.com/17952318/225380057-55bae05e-6387-4d42-9287-07de9f221ba3.png)

**Comment by KostadinovicNikola** [comment]
ça me donne pas ça, après avoir fait le linky auth ..., quand l'acces token expire et que j'essaye de refaire un daily ou autre, ça ne fonctionne pas. Ca affiche Cannot refresh token. Code: 502

**Comment by bokub** [comment]
Je viens de tester à l'instant et tout fonctionne chez moi. Peut-être que tu es tombé à un moment où Enedis était down ?

Est-ce que tu peux réessayer et inclure une capture d'écran du problème ?

**Comment by KostadinovicNikola** [comment]
![bug_linky](https://user-images.githubusercontent.com/73240321/225596782-e4399964-4e1b-4c7c-a9b1-baba488d2724.png)

Voila, le refresh token est valide mais l'acces token est expiré, et ça me fait ça à chaque fois.

**Comment by bokub** [comment]
OK, j'imagine que c'est lié à ton environnement (notebook ?), que je ne connais pas du tout donc je ne vais pas pouvoir t'aider. 

Je t'encourage à utiliser l'outil directement depuis un terminal.

**Comment by KostadinovicNikola** [comment]
J'ai exactement la même erreur sur le terminal.

**Comment by flecoufle** [comment]
C'est Squid qui répond

**Comment by KostadinovicNikola** [comment]
Du coup, est-ce que quelqu'un à des infos concernant ce problème? 
Quand je fais .\linky-win.exe auth -a accestoken-r refreshtoken-u ... . Avec un acces token expiré, j'ai l'erreur envoyé plus haut qui apparait. Je ne sais pas comment régler ça du coup, pour pas avoir à récupérer une nouvelle paire de token toute les 3h.

**Comment by bokub** [comment]
Hello @KostadinovicNikola , il n'y a plus de notion de refresh token depuis la version 2 du module. Je ferme donc cette issue qui est désormais obsolète.

Bonne journée !
