### ISSUE TITLE
Can’t login (have URI changed ?)

### ISSUE THREAD

**Issue by paulgreg** [bokub/linky#5]
Hello,
I’m not able to login, I’m getting « Error: The email or the password is incorrect ».

When looking at the source code, I’m not sure uri [defined line 17](https://github.com/bokub/linky/blob/master/index.js#L17) is valid anymore.

When trying a GET via CURL, I received a 302 redirect to "messages/inexistant.html".
```
curl -XGET -I https://espace-client-connexion.enedis.fr/auth/UI/Login
HTTP/1.1 302 Found
Location: /messages/inexistant.html
```

Does it still work with your credentials ?
What do you think ?

**Comment by bokub** [comment]
The 302 redirect is expected, as you can see in line 24. The goal is just to retrieve the cookie.

I just tried with my credentials and everything is working great

Can you show me what you were trying to do? (Don't forget to hide your real password)

**Comment by paulgreg** [comment]
Ok. Thanks for your quick reply.
I tried linky-cli without any success so I tried to use linky module directly.
I made a very simple script :
```
const linky = require('@bokub/linky');

linky.login("my-enedis-email", "my-enedis-password".then(session => {
    session.getMonthlyData().then(data => {
        console.log(data);
    });
});
```

My enedis password contains a bunch of special characters (via a password generator).
Maybe that’s the problem, I will try to change for a simple one to see if I’m able to use linky.
I’ll keep you in touch.

**Comment by paulgreg** [comment]
Enedis seems to force at least one punctuation character.
Even with a simple password (alpha + num + 1 punctuation sign), I wasn’t able to login via linky or linky-cli.

I’ve got that message via linky-cli : 
npx linky-cli month -u "my-email@free.fr" -p  "my-enedis-password" 
npx: installed 102 in 3.666s
✖ Cannot retrieve consumption
Error: The email or the password is incorrect

It is the same email and password that I use to login into https://mon-compte-particulier.enedis.fr/

Looking more closely on enedis website, I saw that I’m not « completely connected ».
I’m on step 2 « Premiers services », not on step 3 « Tous les services Linky » (see screenshot on https://i.ibb.co/9grMGNK/linky.png).
So maybe that’s the problem !

**Comment by bokub** [comment]
I just tried again with my creds, with the exact same command (`npx linky-cli month -u "my-email@free.fr" -p "my-enedis-password"`) and I have no issue.. 

I don't know what to say, except "wait a few days/weeks and try again" !

**Comment by paulgreg** [comment]
Yes.
I think the issue is about my account.
I think we can close the issue. Thanks again for your work and your time.

My goal is to build an IoT, based on an ESP8266 and a LCD screen to display energy consumption.
The first step is to be able to access my data.

**Comment by opebayle** [comment]
Hello,

I'm trying to do the same, and I've the same result as paulgreg.

> × Cannot retrieve consumption
> Error: The email or the password is incorrect

my login/password work fine on https://mon-compte-particulier.enedis.fr/

Any idea ?

**Comment by bokub** [comment]
Hi @opebayle 
How old is your account ?

**Comment by opebayle** [comment]
I just created it today

**Comment by bokub** [comment]
As said above, you should wait a few days / weeks and try again...

Everything is still working for me today

![image](https://user-images.githubusercontent.com/17952318/81715514-9aa96300-9478-11ea-893f-084445b25df4.png)

**Comment by opebayle** [comment]
Ok thx, I'll wait 👍

**Comment by psa-jforestier** [comment]
Same error here. Account created yesterday. It seems ENEDIS change the way they log user, now they use re-Captcha. 
If you go to https://espace-client-connexion.enedis.fr/auth/UI/Login in a private navigation, you'll be redirerected to a kind of 404 page.

**Comment by WoodySlum** [comment]
Hi, does not work for me since 09 jul. Before, no pb.

**Comment by Skuair** [comment]
> Hi, does not work for me since 09 jul. Before, no pb.

Same for me.

**Comment by bokub** [comment]
Hello :wave: 

I have the same problem myself, I will try to fix it but I don't guarantee anything

**Comment by bokub** [comment]
Bonjour tout le monde

Suite à des suppressions d'endpoints legacy du côté d'Enedis, le module tel qu'il était codé ne pouvait plus fonctionner.

J'ai décidé de tout réécrire from scratch, avec un mécanisme complètement différent.

- Le nouveau module utilise les nouvelles API officielles d'enedis. 
- Il nécessite une étape de consentement qui n'existait pas par le passé.
- J'ai également fusionné le module Node.js et l'outil en ligne de commande
- Enfin, j'ai réécrit la documentation, en français cette fois

Je vous invite à désinstaller l'ancienne version de linky-cli (`npm uninstall -g linky-cli`) et à lire le [README](https://github.com/bokub/linky#readme) pour tous les détails d'installation et d'utilisation

**Comment by WoodySlum** [comment]
Merci pour le taf ! Effectivement l'approche semble plus adaptée.

Par contre ça fait un moment que j'essaye de générer les tokens, et leur API semble complètement buggée - ce soir j'ai une 404.

**Comment by bokub** [comment]
Je viens de tester le workflow complet (génération de tokens + récupération de la conso) et tout fonctionne bien:


![image](https://user-images.githubusercontent.com/17952318/97556311-95fe4a00-19d9-11eb-9b97-3d88fac5a391.png)

Je ferme l'issue

**Comment by opebayle** [comment]
Bonjour,

Je viens de tester aussi ça fonctionne ! Merci pour ce super travail !
