### ISSUE TITLE
Migration API : nouvelle version ?

### ISSUE THREAD

**Issue by PRSoftware** [bokub/linky#50]
Bonjour,

Tout d'abord félicitations et un grand merci pour cette application qui fonctionne très bien et qui remplit parfaitement son rôle.

La date du 30 avril 2023 prévue pour la désactivation des API actuelles arrive à grands pas ...

Est-il toujours prévu une mise à jour de l'application avec les nouvelles API ? 

Si oui, quand avez-vous prévu de rendre disponible cette nouvelle version ?

Cordialement,

Patrick

**Comment by bokub** [comment]
Bonjour,

Suite à un retard énorme du côté d'Enedis, la date du 30 avril a finalement été décalée au 17 septembre, j'ai juste oublié de mettre le README à jour.

Je travaille d'ores et déjà sur la version 2, qui devrait arriver dans les semaines à venir

Bonne journée !

**Comment by bokub** [comment]
Bonjour @PRSoftware ,

Pour information, la version 2 du module permet désormais de passer par les nouvelles API d'Enedis, et de s'affranchir de l'étape de renouvellement des tokens.

Bonne journée !
