### ISSUE TITLE
Erreur depuis 2jours

### ISSUE THREAD

**Issue by xMadNet** [bokub/linky#51]
Bonjour,
Depuis 2 jours plus de données

Note : tokens récupérés juste avant sur le site.
"
Sat Apr 15 10:27:08 pi@Xpi4Test: ~ $ linky auth -a auth -a xxx-r xxx-u xxx
Vos tokens ont été sauvegardés avec succès

Sat Apr 15 10:28:04 pi@Xpi4Test: ~ $ linky loadcurve --start 2023-04-10 --end 2023-04-14
✖ Error from the Enedis API
Code: 500
Response: {
    "error": "Internal Server error",
    "error_description": "Un problème a été rencontré lors du traitement.",
    "error_uri": "https://bluecoder.enedis.fr/api-doc/consulter-souscrire"
}
Probléme ENEDIS ou anomalies ?
Merci

**Comment by bokub** [comment]
Hello,

Très certainement une erreur d'enedis, je t'invite à réessayer dans
quelques jours, et si en fin de semaine c'est toujours cassé j'everrai un
e-mail

Bon week-end !

**Comment by xMadNet** [comment]
Effectivement, cela refonctionne. Pb chez ENEDIS
Merci
