### ISSUE TITLE
Issue with 2.01

### ISSUE THREAD

**Issue by xMadNet** [bokub/linky#53]
==> Update for token
If have to PRM
Getting token is working if get token one by one.

==>still got warning when loadcurve

Hi,
My config : 
Linux TELEINFO 6.1.21-v7+ #1642 SMP Mon Apr  3 17:20:52 BST 2023 armv7l GNU/Linux
node -v v19.8.1

Just update to 2.0.1 : Mise à jour disponible: 1.7.0 → 2.0.1   
Was working before...
 
**Launch
Thu May 11 09:35:58 pi@TELEINFO: ~ $ linky loadcurve  --prm xxprm1xx --start 2023-05-02 --end 2023-05-09
(node:6086) ExperimentalWarning: Import assertions are not a stable feature of the JavaScript language. Avoid relying on their current behavior and syntax as those might change in a future version of Node.js.
(Use `node --trace-warnings ...` to show where the warning was created)
(node:6086) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
Vous n'avez aucun token enregistré.
Lancez 'linky auth' pour vous connecter ou renseignez le paramètre --token

** Token get through new URL https://conso.boris.sh/
Got error
{"status":403,"message":"Accès au PRM non autorisé","query":"xxprm1xx","verified":"xxprm1xx,xxprm2x","detail":"Prenez un screenshot de cette erreur et envoyez-la moi svp, merci !"}

Merci pour ton aide

**Comment by bokub** [comment]
Hello,

Je viens de déployer un fix, peux-tu réessayer de générer un token sur [conso.boris.sh](https://conso.boris.sh/) ?

**Comment by xMadNet** [comment]
Hello,
Le fix marche avec les 2 PRM sélectionnés. Merci
Reste les warning au lancement :-)
(node:7358) ExperimentalWarning: Import assertions are not a stable feature of the JavaScript language. Avoid relying on their current behavior and syntax as those might change in a future version of Node.js.
(Use `node --trace-warnings ...` to show where the warning was created)
(node:7358) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time

**Comment by bokub** [comment]
Pour éviter les warnings, tu peux lancer `NODE_NO_WARNINGS=1 linky loadcurve` au lieu de juste `linky loadcurve`.

Ce sera corrigé dans la prochaine version (2.0.2) donc c'est temporaire.

**Comment by bokub** [comment]
@xMadNet Je viens de publier la version `2.0.2`, normalement plus de warnings

**Comment by xMadNet** [comment]
Super. Merci
