### ISSUE TITLE
Unexpected identifier

### ISSUE THREAD

**Issue by bohwaz** [bokub/linky#54]
Après une installation avec npm i -g linky j'ai cette erreur :

```
file:///home/bohwaz/.local/lib/node_modules/linky/dist/bin/cli.js:7
import pkg from '../package.json' assert { type: 'json' };
                                  ^^^^^^

SyntaxError: Unexpected identifier
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
    at async link (internal/modules/esm/module_job.js:42:21)
```

**Comment by bokub** [comment]
Salut @bohwaz,
Quelle est ta version de node s'il te plaît ?

(tu peux faire `node --version` pour avoir la réponse)

**Comment by bohwaz** [comment]
12.22.5

Je clos car du coup j'ai codé mon propre script, merci :)

**Comment by bokub** [comment]
OK je pense que tu peux faire une petite mise à jour, Node 12 n'est plus maintenu depuis plus d'un an, et Node 14 depuis fin avril.

La version 2 de ce module nécessite à minima la version 16, sachant que la version actuelle de Node est la version 20

**Comment by bohwaz** [comment]
Peut-être du coup l'exiger dans le package.json ?

Je suis sous Debian stable, Node 12 est la version fournie, et toujours maintenue, dernière mise à jour en janvier, pour info :)

**Comment by bokub** [comment]
> Peut-être du coup l'exiger dans le package.json ?

Oui c'est déjà le cas: 

https://github.com/bokub/linky/blob/3ba8c2cc273b1ff720549c4b37e997852c349355/package.json#L15-L17

> Je suis sous Debian stable, Node 12 est la version fournie

Je sais pas comment tu as installé Node, mais si tu veux utiliser un package manager, tu dois passer par les versions binaires fournies par [NodeSource](https://github.com/nodesource/distributions#debian-and-ubuntu-based-distributions), et pour ça tu dois lancer un petit script avant chaque installation en fonction de la version que tu veux.

Par exemple pour Node 18 sous Debian, tu dois faire (en tant que root):

```bash
curl -fsSL https://deb.nodesource.com/setup_lts.x | bash - &&\
apt-get install -y nodejs
```

> et toujours maintenue, dernière mise à jour en janvier, pour info :)

ça m'étonnerait beaucoup, ta version de Node a été publiée en [août 2021](https://nodejs.org/en/blog/release/v12.22.5). Peut-être qu'elle a été re-compilée en janvier ou ré-uploadée, mais ça ne signifie pas qu'elle est maintenue

Bonne journée et bonne mise à jour :slightly_smiling_face:

**Comment by bohwaz** [comment]
Elle est maintenue par Debian.

Perso je n'utilise que les paquets fournis par la distro, hors de question d'installer des trucs qui te disent d'exécuter des scripts en root, très mauvaise pratique de sécurité :)

Merci tout de même, bonne journée aussi :)
