### ISSUE TITLE
Erreur d'installation node module sur projet Symfony

### ISSUE THREAD

**Issue by RedPandore** [bokub/linky#55]
Bonjour,

J'essaye actuellement d'integré votre module sur un projet symfony. 
Après l'installation, lorsque je lance mon serveur node via npm, ce dernier trouve 10 erreurs.

Module build failed: Module not found:
    "./node_modules/jsonwebtoken/sign.js" contains a reference to the file "crypto".
    This file can not be found, please check it for typos or update it if the file got moved.

    "./node_modules/jwa/index.js" contains a reference to the file "crypto".
    This file can not be found, please check it for typos or update it if the file got moved.

    "./node_modules/jwa/index.js" contains a reference to the file "util".
    This file can not be found, please check it for typos or update it if the file got moved.

    "./node_modules/jws/lib/data-stream.js" contains a reference to the file "stream".
    This file can not be found, please check it for typos or update it if the file got moved.

    "./node_modules/jws/lib/data-stream.js" contains a reference to the file "util".
    This file can not be found, please check it for typos or update it if the file got moved.

webpack compiled with 10 errors

J'ai donc installer les package manquant :

- npm i util
- npm i stream
- npm i crypto-browserify

Puis j'ai modifier ma config webpack afin de chargé "crypto-browserify" à la place de "crypto".

` [...]
module.exports = Encore.getWebpackConfig();
 
module.exports.resolve.fallback = {
    crypto: require.resolve('crypto-browserify')
};
`

À ce stade, mon serveur ce lance sans erreur, mais lorsque j'essaye le module, je ne récupère aucune données et j'ai ce message dans la console : " Uncaught ReferenceError: process is not defined "

**edit**

J'ai effectué : 
npm i process

puis dans le fichier webpack.config.js j'ai ajouter deux lignes : 

const webpack = require('webpack');
.addPlugin(new webpack.ProvidePlugin({
        process: 'process/browser',
}))

Maintenant j'ai un problème avec la requête, cette dernière est bloqué par le header : Cross-Origin Request. 

J'ai essayé de modifier ma config sur cette parti mais rien n'y fait. 
Je continu les recherches de mon côté, j'éspère trouver une solution.

**Comment by bokub** [comment]
Hello,

Le module n'est pas fait pour tourner dans un navigateur, mais sur un serveur Node.js ! Vu que tu fais du PHP, je ne pense pas que ce module soit fait pour toi.

En revanche, tu peux appeler directement [Conso API](conso.boris.sh) depuis ton serveur Symfony: https://conso.boris.sh/documentation

**Comment by RedPandore** [comment]
Salut,

Je pensais pouvoir le faire fonctionner en jouant sur la config. Mais effectivement, si je peux interrogé l'api directement depuis PHP autant en profiter !

En tout cas, merci pour ton aide et surtout pour ton travail.
