### ISSUE TITLE
"ADAM-ERR0069"

### ISSUE THREAD

**Issue by Pat5488** [bokub/linky#56]
Bonjour,
lorsque j'essaye de relever ma production PV j'obtient le message d'erreur suivant: (je produit depuis le 2 mai et j'ai injecté 100kWh sur le réseau.

......> linky loadcurveprod
× Conso API a répondu avec une erreur
× Code: 400
× Réponse: {
    "status": 400,
    "message": "The Enedis API returned an error",
    "error": {
        "error": "ADAM-ERR0069",
        "error_description": "Le sens de la mesure ne correspond pas pour le PRM demandé"
    }
}

Merci pour votre aide, Pat.

**Comment by bokub** [comment]
Salut,
Je pense que tu n'utilises pas le bon PRM

**Comment by bokub** [comment]
Salut,
Je pense que tu requêtes les donnés du mauvais PRM.
À tout hasard ton token ne permettrait-il pas d'accéder à 2 PRM ? (un pour la consommation et un pour la production)

**Comment by Pat5488** [comment]
Mon Token fonctionne bien pour relever ma consommation mais je ne parviens pas à relever la production

**Comment by bokub** [comment]
Oui j'ai bien compris, mais est-ce que ton token permet d'accéder à plusieurs PRM ? Normalement tu as cette info après l'étape de consentement Enedis

**Comment by Pat5488** [comment]
Bonjour, non avec mon token je me connecte à un seul PRM

**Comment by bokub** [comment]
OK, je sais pas trop comment ça fonctionne la production d'électricité mais si j'ai bien compris tu est censé avoir un autre PRM pour ta production. Est-ce que tu peux accéder aux données de production sur [ton espace client Enedis](https://mon-compte-client.enedis.fr/) ? Est-ce que tu peux ajouter ce PRM sur l'écran de consentement ?

![image](https://github.com/bokub/linky/assets/17952318/6278eef5-b4cc-47b2-bf0a-c5e607e4aa4f)

**Comment by Pat5488** [comment]
J'ai appelé ENEDIS, en fait mon installation n'est pas encore en service de leur côté, d'où l'erreur...
Pour info, je suis en mode autoconsommation avec revente du surplus, il n'y a qu'un seul PRM.
Je n'ai plus qu'a attendre ENEDIS, le sujet est clos, merci!
