### ISSUE TITLE
Conso API erreur ADAM-DC-0008

### ISSUE THREAD

**Issue by Pat5488** [bokub/linky#57]
Bonjour,

lorsque j'interroge ma production quotidienne j'obtiens l'erreur suivante:

C:\Users\patki>linky_ dailyprod
× Conso API a répondu avec une erreur
× Code: 403
× Réponse: {
    "status": 403,
    "message": "The Enedis API returned an error",
    "error": {
        "error": "ADAM-DC-0008",
        "error_description": "No consent can be found for this customer and this usage point."

Quelqu'un connait il la signification de ce message?
        
Sur l'application mobile ou web tout est OK je vois bien ma production journalière.

Pat

**Comment by bokub** [comment]
Hello Pat,

Est-ce qu'au moment du consentement tu as donné accès au compteur de production ? Peux-tu m'envoyer une capture d'écran du consentement que je puisse mieux comprendre ?

Merci

**Comment by Pat5488** [comment]
Bonjour Boris,

quand j'ai donné le consentement je n'étais pas encore en production c'est peut-être cela le problème...?
Avec mon Token j'arrive bien à charger toute mes données de consommation mais pas la production.

Quand j'essaye d'accéder à Enedis depuis ta page "conso.boris.sh" j'ai ce message d'erreur:

![image](https://github.com/bokub/linky/assets/118670289/e07c36a1-dfa4-478e-87fb-82741b4ed14c)

Je ne peux créer pas un nouveau Token!

Pat

**Comment by garnierph** [comment]
Bonjour,

J'ai depuis quelques jours le même problème que Pat à savoir "500 Internal Server Error". Impossible donc de regénérer mes tokens.
 
Philippe

**Comment by bokub** [comment]
Bonjour @garnierph , 

Ce repository GitHub concerne uniquement l'outil CLI + le module Node.js `linky`, pas Conso API, et encore moins les problèmes d'Enedis

Votre problème est déjà référencé ici: https://github.com/bokub/conso-api/issues/3, et comme indiqué, l'erreur est sur la page de consentement codée par Enedis, je ne peux malheureusement rien y faire

**Comment by Pat5488** [comment]
![image](https://github.com/bokub/linky/assets/118670289/53032281-73f5-4efa-b08d-defed92ae855)

La page est revenue ce soir chez ENEDIS , mais la validation ne semble pas fonctionner....

**Comment by Pat5488** [comment]
Je peux maintenant charger ma production sans message d'erreur, l'incident est clos
![image](https://github.com/bokub/linky/assets/118670289/29ac5e3b-a4ab-498c-bcf7-577a15271259)
