### ISSUE TITLE
Permettre d'afficher les données d'une tranche horaire précise sur un intervalle de jours

### ISSUE THREAD

**Issue by damien-louis** [bokub/linky#62]
Tout d'abord, merci pour cet outil super intéressant.

J'ai une proposition : j'aimerai pouvoir comparer sur une période de plusieurs jours ma conso, par exemple, entre 12h00 et 14h00
La requête nécessiterait un jour de début, un jour de fin, une heure de début, une heure de fin genre : 

`linky {nom de la fonction} --start 2023-12-01 --end 2023-12-05 --start-time 12:00 --end-date 14:00`

La valeur affichée serait la **somme** des périodes : 
12:00 + 12:30 + 13:00 + 13:30 

Il faudrait évidemment pouvoir arrondir (et prévenir l'arrondi choisi) si l'heure saisie n'est pas en :00 ou :30

Et l'affichage serait de ce style : 

| Date  | Valeur (W)          | Graphique  |
| :--------------- |:---------------:| :-----|
| 2023-12-01  |   1800        |  XXXXXXXXXX  |
| 2023-12-02  |   1950        |  XXXXXXXXXXXX  |
| 2023-12-03  |   1400        |  XXXXXXX  |
| 2023-12-04  |   1800        |  XXXXXXXXXX  |
| 2023-12-05  |   2500        |  XXXXXXXXXXXXXXX  |

Qu'en pensez-vous ?

**Comment by bokub** [comment]
Salut !
Je comprends tout à fait le besoin, mais je trouve qu'il est vraiment trop spécifique pour mériter d'être intégré à ce module.

En effet, si je rajoute ça, pourquoi pas aussi les sommes par semaine ou par mois, les moyennes, les min et max, etc... Il existe des dizaines d'analyses intéressantes à faire mais si je les rajoute à chaque fois que quelqu'un réclame ça va devenir une usine à gaz à maintenir mais aussi à documenter (le but c'est que la CLI reste simple d'utilisation pour les plus novices) 

Bref, le but de ce module c'est surtout de récupérer les données d'enedis **avec le moins de transformation possible**, pas vraiment d'offrir des outils d'analyse ! 

De plus, je pense que tu peux obtenir ce que tu veux avec un script bash (ou autre) de quelques lignes, donc quelque chose de beaucoup plus personnalisable et adapté à tes besoins 

Merci quand même pour cette suggestion et bonne journée !

**Comment by damien-louis** [comment]
OK, merci pour ta réponse
