### ISSUE TITLE
Option tempo

### ISSUE THREAD

**Issue by DaeroValoti** [bokub/linky#63]
Bonjour, 

Je soumets une potentielle demande de nouvelle feature ou enrichissement de la documentation si possible.
Avec l'option TEMPO d'EDF, nous avons un tarifs à la journée dépendant d'une couleur Bleu, Blanc ou Rouge.

Est-ce possible de récupérer cette caractéristique ou c'est complètement lié à EDF et donc Enedis n'est pas du tout en mesure de récupérer cette information ?

**Comment by bokub** [comment]
Hello!

Tu as bien deviné, Enedis s'occupe uniquement de la distribution de l'électricité, et n'est pas au courant des modalités de contrat ou de facturation (ou du moins ne les met pas à disposition), donc je ne peux pas fournir cette information

**Comment by bokub** [comment]
En revanche je crois avoir entendu parler d'une API dédiée à l'option tempo, utilisée par exemple par ce repo: https://github.com/hekmon/rtetempo

**Comment by DaeroValoti** [comment]
Merci.
Au final, comme c'est compliqué de parser le site EDF.
J'ai trouvé une petite alternative qui marche très bien (c'est à améliorer bien sûr, moi çà me suffit).

url = 'https://www.keskeces.fr/couleur-du-jour-edf-tempo.html'
contenu = urllib.request.urlopen(url, context=context).read()
soup = BeautifulSoup(contenu,"lxml")

colors = soup.find_all("div", { "class" : "bj" })
color_today = colors[1].text

if "Bleu" in color_today:
    final_color_to_insert = "Bleu"
elif "Blanc" in color_today:
    final_color_to_insert = "Blanc"
elif "Rouge" in color_today:
    final_color_to_insert = "Rouge"

print(final_color_to_insert)
