### ISSUE TITLE
Erreur 400

### ISSUE THREAD

**Issue by rockketlauncher** [bokub/linky#64]
Bonjour,
J'ai bien récupéré le token mais au moment de lancer la requête j'ai des erreurs:
 Conso API a répondu avec une erreur
```
Code: 400
Réponse: {
    "status": 400,
    "message": "Paramètres invalides",
    "error": {
        "issues": [
            {
                "code": "too_big",
                "maximum": 14,
                "type": "string",
                "inclusive": true,
                "exact": true,
                "message": "String must contain exactly 14 character(s)",
                "path": [
                    "prm"
                ]
            }
        ],
        "name": "ZodError"
    }
```

Une idée ?

**Comment by bokub** [comment]
Salut,

Je pense qu'en analysant le message 30 secondes du pouvais trouver par toi-même (sauf si tu ne parles vraiment aucun mot d'anglais) :smile: 

> "Paramètres invalides"

> "prm"

> "too_big"

> String must contain exactly 14 character(s)

En gros le paramètre `prm` est invalide car il doit faire 14 caractères et celui que tu m'as fourni est plus grand

**Comment by rockketlauncher** [comment]
Salut,
J'ai bien 14 chiffres pour le numéro du PRM et pas plus ni moins.
Quand je lance la commande en précisant le numéro de PRM (j'en ai 2)  avec l'option --prm
"Ce token ne permet pas d'accéder au PRM ......".
J'ai l'impression que quelque chose c'est mal passé.
Et si j'enregistre le token j'ai: "Votre token a été sauvegardé avec succès".
Je ne vois rien apparaitre sur mon compte Enedis mis à part que les données sont partagées.
Merci

**Comment by bokub** [comment]
Tu peux peut-être partager les commandes ou le code que tu utilises et qui mène à cette erreur ? Là j'ai vraiment pas assez de détail pour te dire ce qui ne va pas

**Comment by bokub** [comment]
D'ailleurs, je profite du fait que tu sois l'heureux propriétaire de plusieurs PRMs

Pourrais-tu s'il te plaît régénérer un nouveau token en prenant soin de bien cocher TOUS les compteurs ? Et quand c'est fait m'envoyer la date et heure de ton action ? 

Ce serait super sympa car j'aimerais voir si Enedis a corrigé leur bug (il parait que oui), mais je ne possède qu'un compteur

**Comment by bokub** [comment]
OK ne n'embête pas, je viens de comprendre ce qui se passe

Enedis vient de corriger leur bug pour les multi PRMs alors que ça n'a jamais fonctionné dans le passé. 

Ils renvoient la liste des compteurs en séparant tes numéros de PRM par un point virgule, mais du coup ce qui est enregistré dans ton token c'est que tu as accès à un PRM imaginaire de 29 caractères (2x 14 + le point virgule), au lieu de 2 PRMs distincts.

Je corrige et je te fais signe !

**Comment by bokub** [comment]
@rockketlauncher C'est bon c'est réparé ! Tu vas devoir re-générer un token sur Conso API, celui que tu possédais est invalide

**Comment by rockketlauncher** [comment]
je vais ressayer plus tard dans la soirée car maintenant quand je souhaite faire un partage de donnée de compteurs sur le site Enedis, mes compteurs sont grisé et noté "incompatible"....je te tiens au courant dès que ca remarche côté Enedis.

**Comment by bokub** [comment]
Oui j'ai pareil que toi. 

C'est fatiguant de voir que c'est nos impôts qui financent un service aussi instable mais c'est pas le sujet 😢

**Comment by rockketlauncher** [comment]
oui ils ont des progrès à faire car j'ai voulu ouvrir un incident pour des coupures électriques dans le quartier il y a environ 1 an et lorsque j'ai rempli le formulaire en ligne il n'était pas fichu de compter le nombre de caractère alors que j'avais bien écris et au bout de plusieurs essais pendant plusieurs jours, je me suis posé la question si c'était pas parce que j'avais mis des dates dans le formulaire avec des "/"....et bien oui...si il y a un "/" c'est comme si rien était écris :) c'est pas le sujet non plus mais bon arrivé en 2023 et avoir un formulaire qui ne prend pas en compte des caractères spéciaux...retour en l'an 2000.

**Comment by rockketlauncher** [comment]
Bonjour,
Après plusieurs semaines cela ne semble plus fonctionner, sur le site Enedis c'est noté que mon compteur est incompatible.
J'ai tenté la désactivation de la collecte puis la réactivation mais rien de mieux.

**Comment by bokub** [comment]
https://github.com/bokub/conso-api/issues/26

**Comment by rockketlauncher** [comment]
Bonjour, Il y a une adresse mail à laquelle écrire à Enedis pour leur signaler  que cela ne fonctionne plus ?
(j'ai peut-être la possibilité de trouver un contact chez eux, je travaille dans le même groupe , si ca peut aider à faire avancer )

**Comment by DSAndreee** [comment]
+1 J'ai le même soucis. Si on peut être plusieurs à écrire ça peut peser ! En tout cas merci pour le travail hâte de tester et de faire des PR au besoin :)

**Comment by bokub** [comment]
Perso j'écris à `serviceclients-api@enedis.fr` mais j'ai déjà posé une question de sécurité (donc assez sérieux) à laquelle ils ont répondu après plus de 9 mois (malgré 4 relances) ... qu'ils n'avaient pas de solution :shrug: 

Si vous avez une autre adresse avec des interlocuteurs un peu plus réveillés, je suis preneur

**Comment by DSAndreee** [comment]
Hello @bokub 

En testant avec une autre application que Conso API, j'ai bien tout qui fonctionne ! Lien d'exemple : [https://mon-compte-particulier.enedis.fr/dataconnect/v1/oauth2/authorize?client_id=0dbeb7b3-a0d9-4f84-ae20-1822e1d35093&state=fz80ac783&duration=P3Y&response_type=code](https://mon-compte-particulier.enedis.fr/dataconnect/v1/oauth2/authorize?client_id=0dbeb7b3-a0d9-4f84-ae20-1822e1d35093&state=fz80ac783&duration=P3Y&response_type=code)

Ils ont peut-être modifié leur auth ? J'ai envoyé un mail en attendant tout de même

![image](https://github.com/bokub/linky/assets/9129859/a63e06a3-9185-4483-8132-29fc27357f4e)

**Comment by DSAndreee** [comment]
Par ailleurs lorsque l'on regarde les échanges réseau, on voit une grosse différence sur le JSON qui contient les informations d'authentification : 

**Fonctionnel (enedis-box-domotique) :**

`{
    "contexts": {
        "DATA_CONTRACTUELLE": [
            "IDENTITY",
            "CONTACT",
            "CONTRACTS",
            "ADDRESSES"
        ],
        "DATA_CONS": [
            "CONSO_QUOTIDIENNE",
            "CONSO_DEMI_HEURE",
            "PUISSANCE_MAXI_CONSO"
        ],
        "DATA_PROD": [
            "PROD_DEMI_HEURE",
            "PROD_QUODITIENNE"
        ]
    },
    "idPersonne": "XXXXXXXXXXXX",
    "idTiers": "XXXXXXXXXXXX",
    "listPrmAdresse": [
        {
            "adresse": "X YYYYYYYYY ZZZZZ (mon adresse)",
            "prm": "XXXXXXXXXXXXXX (mon prm)",
            "segment": "C5"
        }
    ],
    "logo": null,
    "messageError": null,
    "nomTiers": "enedis-box-domotique",
    "redirectUri": "http://www.sud-domotique-expert.fr/enedis/traite_retour_accord_enedis.html",
    "status": 0
}` 

**Non fonctionnel (Conso API) :** 

`{
    "contexts": null,
    "idPersonne": "XXXXXXXXXXXX",
    "idTiers": null,
    "listPrmAdresse": [
        {
            "adresse": "X YYYYYYYYY ZZZZZ (mon adresse)",
            "prm": "XXXXXXXXXXXXXX (mon prm)",
            "segment": "C5"
        }
    ],
    "logo": null,
    "messageError": null,
    "nomTiers": null,
    "redirectUri": null,
    "status": 0
}`

Si jamais ça peut aider ! Je pense qu'il y'a un soucis avec ton application peut-être ?

**Comment by bokub** [comment]
> Si jamais ça peut aider ! Je pense qu'il y'a un soucis avec ton application peut-être ?

Oui, très probablement, mais **je ne peux rien y faire**, je bosse pas chez Enedis et c'est une page hébergée chez **Enedis** ! 

J'ai juste accès à un pauvre dashboard tout buggué où je peux changer le nom / la description de l'appli, et accéder à une `APP_ID` et un `APP_SECRET`. Ce sont les **seules** actions que je peux faire qui pourraient avoir un impact sur la page de consentement.

**Comment by DSAndreee** [comment]
D'acc merci @bokub !

J'ai fait une demande pour avoir ma propre application je te dirai si ça fonctionne de mon côté une fois le contrat signé !

Encore merci pour ton temps :)

**Comment by bokub** [comment]
OK ! Pour poursuivre la conversation concernant l'obtention d'un token, svp faites-le là bas, et pas sur cette issue qui concernait une erreur 400

https://github.com/bokub/conso-api/issues/26

Merci !

**Comment by rockketlauncher** [comment]
Bonjour,
J'ai eu une réponse de Enedis avec mon mail pro et ils ont besoin de détail sur l'application:
_**Nous accusons réception de votre demande, cependant nous ne pouvons y donner suite. En effet, un problème connu est en cours de résolution, mais pour pouvoir investiguer sur tout incident, nous avons besoin des détails de l’application utilisatrice, il faut donc que vous fassiez remonter votre demande au responsable de l’application , qui pourra nous communiquer les détails nécessaires. 
Normalement, une première mise à jour le 25/01/2024 devrait résoudre une partie des problèmes concernant le don de consentement. 
Espérant avoir apporté un peu de lumière sur votre problème, nous restons à votre écoute.**_

Je peux mettre en relation par mail si besoin d’échanger plus facilement avec un contact Enedis.

**Comment by bokub** [comment]
Merci c'est gentil, mais comme indiqué dans mon précédent message, il y a déjà une issue à propos du don de token **ici**:
https://github.com/bokub/conso-api/issues/26

Là on est sur le repository du module Node.js `linky`, tous les soucis que vous remontez concernent l'API et pas le module qui permet d'appeler cette API !
