### ISSUE TITLE
Impossible de définir un prix

### ISSUE THREAD

**Issue by killkuter** [bokub/linky#65]
Bonjour,
je ne sais pas si c'est lié au module ou plus à HA lui même, j'ai bien intégré le tout dans le tableau d'énergie mais il m'est impossible de définir un prix prix fixe ou lié à une entité une fois que j'ai sélectionné le module comme source, les 2 options sont grisés.
Par contre je peux les définir avant de sélectionner le lien avec mon compteur mais du coup il n'y a pas de coût dans le dashboard énergie.
Est ce normal ? Suis je le seul dans ce cas ?

Merci d'avance

![image](https://github.com/bokub/linky/assets/153915733/1581b7a1-6ac6-4df9-b62f-fbae4f451bbb)

**Comment by bokub** [comment]
Hello, tu n'est pas du tout dans le bon repository, ici c'est un module Node.js pour récupérer de la donnée en ligne de commande, alors que visiblement ton souci concerne [HA Linky](https://github.com/bokub/ha-linky)...

Je t'invite à aller lire cette issue: https://github.com/bokub/ha-linky/issues/2
