### ISSUE TITLE
Erreur 404

### ISSUE THREAD

**Issue by XDECO** [bokub/linky#66]
Bonjour

HA Est bien connecteé à Lincky par contre il y une erreur 404 ci-dessous le fichier Log

Merci pour votr aide

```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
HA Linky is starting
Connection with Home Assistant established
PRM 09391027447472 found in configuration for consumption
[09/02 13:51] Synchronization started for consumption data
Last saved statistic date is 08/02/2024
Everything is up to date, nothing to synchronize
Data synchronization planned every day at 06:50:55 and 09:50:55
Connection with Home Assistant closed
Connection with Home Assistant established
[10/02 06:50] Synchronization started for consumption data
Last saved statistic date is 08/02/2024
Cannot fetch consumption load curve from 2024-02-09 to 2024-02-10, here is the error:
Conso API a répondu avec une erreur
Code: 404
Réponse : {
    "status": 404,
    "message": "The Enedis API returned an error",
    "error": {
        "error": "no_data_found",
        "error_description": "no measure found for this usage point"
    }
}
Data import returned nothing !
Connection with Home Assistant closed
Connection with Home Assistant established
[10/02 09:50] Synchronization started for consumption data
Last saved statistic date is 08/02/2024
Cannot fetch consumption load curve from 2024-02-09 to 2024-02-10, here is the error:
Conso API a répondu avec une erreur
Code: 404
Réponse : {
    "status": 404,
    "message": "The Enedis API returned an error",
    "error": {
        "error": "no_data_found",
        "error_description": "no measure found for this usage point"
    }
}
Data import returned nothing !
Connection with Home Assistant closed
Connection with Home Assistant established
[11/02 06:50] Synchronization started for consumption data
Last saved statistic date is 08/02/2024
Cannot fetch consumption load curve from 2024-02-09 to 2024-02-11, here is the error:
Conso API a répondu avec une erreur
Code: 404
Réponse : {
    "status": 404,
    "message": "The Enedis API returned an error",
    "error": {
        "error": "no_data_found",
        "error_description": "no measure found for this usage point"
    }
}
Data import returned nothing !
Connection with Home Assistant closed
Connection with Home Assistant established
[11/02 09:50] Synchronization started for consumption data
Last saved statistic date is 08/02/2024
Cannot fetch consumption load curve from 2024-02-09 to 2024-02-11, here is the error:
Conso API a répondu avec une erreur
Code: 404
Réponse : {
    "status": 404,
    "message": "The Enedis API returned an error",
    "error": {
        "error": "no_data_found",
        "error_description": "no measure found for this usage point"
    }
}
Data import returned nothing !
Connection with Home Assistant closed
```

**Comment by bokub** [comment]
Salut,

Est-ce que tu arrives à récupérer des données depuis [la page exemples de Conso API ](https://conso.boris.sh/exemples)?

Et est-ce que tu vois des données dans ton espace client Enedis ?

**Comment by XDECO** [comment]
Salut

Je viens de tester et ça fonctionne depuis la pages exemples de conso API

Cdlt

Xavier

**Comment by bokub** [comment]
T'as bien essayé de récupérer la courbe de charge (consommation par demi-heure) ?  Pour les mêmes dates ?

Si oui y'a moyen d'avoir un petit screenshot parce que là j'ai vraiment un gros doute

**Comment by XDECO** [comment]
Effectivement avec la courbe de charge j’ai la même erreur que sur HA
Avec la page test ça ne fonctionne que pour la consommation quotidienne et
puissance maximal de consommation

Voici le screen shot

**Comment by bokub** [comment]
Je vois pas de screenshot mais pas grave je me doutais bien que Conso API retournerait la même erreur.

Tu n'as toujours pas répondu à ma question: Et est-ce que tu vois ta courbe de charge dans ton espace client Enedis ?

**Comment by XDECO** [comment]
Oui j'arrive a lire mes donnés journalière sur mon compte Enedis, en
pièce jointe un screen shot

Seul les données en semaine et journaliére sont disponible pour mois

**Comment by bokub** [comment]
Si tu ne vois pas tes données chez Enedis c'est normal que tu ne puisses pas y accéder via Conso API...

Il faut que tu ailles dans ton espace client Enedis, en bas de la page "Gérer l’accès à mes données", et que tu actives:
- l'enregistrement de la consommation horaire
- la collecte de la consommation horaire

Ensuite ça devrait marcher

**Comment by XDECO** [comment]
Bonjour et encore merci pour ton aide

Je crois avoir compris pourquoi ça ne marche pas chez moi, en effet pour
l'instant je ne dispose que des premiers services Linky à savoir le relevé
du compteur à distance, le relevé des données journalière, mensuelle et
annuelle. Je viens de tester à nouveau avec la fonction test de Conso API
et dans ce cas je récupère bien les données.
Par contre, l'accès au donnés horaire et la gestion de l'accès à mes
données ne sera possible que dans quelques temps (voir screenshot en
pièce jointe).
Je suppose que pour utiliser ton intégration il faut bénéficier de tous les
services linky et que je ne peux pas configurer seulement l'accès au
premier service Linky le temps qu' Enedys me mette à disposition tous les
services Linky.

Cordialement

Xavier
