### ISSUE TITLE
The Enedis API returned an error

### ISSUE THREAD

**Issue by Bo0Ki** [bokub/linky#67]
Bonjour,

J'essaye depuis 2 jours d'activer mon suivi sur home assistant, j'ai cependant une erreur API de enedis. Si quelqu'un a une solution..
Voici le log de ha-linky :

[16/02 10:13] Synchronization started for consumption data
Last saved statistic date is 14/02/2024
Cannot fetch consumption load curve from 2024-02-15 to 2024-02-16, here is the error:
Conso API a répondu avec une erreur
Code: 404
Réponse : {
    "status": 404,
    "message": "The Enedis API returned an error",
    "error": {
        "error": "no_data_found",
        "error_description": "no measure found for this usage point"
    }
}
Data import returned nothing !
Data synchronization planned every day at 06:04:46 and 09:04:46
Connection with Home Assistant closed

Si vous avez une idée je suis preneur.
Merci

Je viens de me rendre compte que je ne suis pas sur le bon github. Mais ne peux supprimer.

**Comment by jeandavid59** [comment]
Bonjour,
J:ai exactement ce même message quand le lance le module.

s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
HA Linky is starting
Connection with Home Assistant established
PRM 14367148960217 found in configuration for consumption
[29/02 18:29] Synchronization started for consumption data
Last saved statistic date is 21/02/2024
Cannot fetch consumption load curve from 2024-02-22 to 2024-02-29, here is the error:
Conso API a répondu avec une erreur
Code: 404
Réponse : {
    "status": 404,
    "message": "The Enedis API returned an error",
    "error": {
        "error": "no_data_found",
        "error_description": "no measure found for this usage point"
    }
}
Data import returned nothing !
PRM 14276266191182 found in configuration for consumption
[29/02 18:29] Synchronization started for consumption data
Last saved statistic date is 22/02/2024
Cannot fetch consumption load curve from 2024-02-23 to 2024-02-29, here is the error:
Conso API a répondu avec une erreur
Code: 404
Réponse : {
    "status": 404,
    "message": "The Enedis API returned an error",
    "error": {
        "error": "no_data_found",
        "error_description": "no measure found for this usage point"
    }
}
Data import returned nothing !
Data synchronization planned every day at 06:14:39 and 09:14:39
Connection with Home Assistant closed

Par contre si je lance dans un terminal 
la commande 
curl -X GET \
    'https://conso.boris.sh/api/daily_consumption?prm=MON_PRM&start=2024-02-22&end=2024-02-29' \
    -H 'Authorization: Bearer MON_TOKEN'
j'obtiens le  resultat
{"usage_point_id":"MON_PRM","start":"2024-02-22","end":"2024-02-29","quality":"BRUT","reading_type":{"unit":"Wh","measurement_kind":"energy","aggregate":"sum","measuring_period":"P1D"},"interval_reading":[{"value":"14507","date":"2024-02-22"},{"value":"19530","date":"2024-02-23"},{"value":"21538","date":"2024-02-24"},{"value":"21717","date":"2024-02-25"},{"value":"19270","date":"2024-02-26"},{"value":"17995","date":"2024-02-27"},{"value":"19760","date":"2024-02-28"}]}
J'ai vérifié plusieurs le prm et le token dans le fichier de config et tous deux sont corrects.

Merci de votre aide.

**Comment by bokub** [comment]
En effet t'es vraiment pas du tout au bon endroit

Celle issue non plus mais déjà un peu mieux: https://github.com/bokub/ha-linky/issues/29
