### ISSUE TITLE
SyntaxError: Unexpected identifier 'assert'

### ISSUE THREAD

**Issue by si2w** [bokub/linky#69]
Do anyone had this issue (Sonoma 14.4.1 on Apple Silicon)?

```
linky
file:///opt/homebrew/lib/node_modules/linky/dist/bin/cli.js:7
import pkg from '../package.json' assert { type: 'json' };
                                  ^^^^^^

SyntaxError: Unexpected identifier 'assert'
    at compileSourceTextModule (node:internal/modules/esm/utils:338:16)
    at ModuleLoader.moduleStrategy (node:internal/modules/esm/translators:103:18)
    at #translate (node:internal/modules/esm/loader:433:12)
    at ModuleLoader.loadAndTranslate (node:internal/modules/esm/loader:480:27)
    at async ModuleJob._link (node:internal/modules/esm/module_job:112:19)

Node.js v23.1.0
```

**Comment by bokub** [comment]
What's your node version?

**Comment by bokub** [comment]
Hello 

https://stackoverflow.com/questions/78876691/syntaxerror-unexpected-identifier-assert-on-json-import-in-node-v22

Apparently, node 23 doesn't support "assert" anymore...

**Comment by si2w** [comment]
Indeed. Do you plan to fix this in a new version ?

**Comment by bokub** [comment]
Yeah probably later, but not right now I'm on holidays

**Comment by si2w** [comment]
Enjoy your holidays. Thanks for the good work

**Comment by bokub** [comment]
Hello @si2w 

Version 2.1.0 should fix your problem!

Thanks for your patience

**Comment by si2w** [comment]
Hello @bokub 

It works like a charm. 

Thanks for the awesome work
