### ISSUE TITLE
Génération token pour compte entreprise

### ISSUE THREAD

**Issue by wpchannel** [bokub/linky#73]
Je cherche à récupérer les données en CLI pour un compte entreprise. Est-ce supporté ?

**Comment by bokub** [comment]
Salut,
Comme indiqué dans #22, non ce n'est pas possible

**Comment by wpchannel** [comment]
D'accord, y compris avec [Jeton V3](https://datahub-enedis.fr/services-api/data-connect/documentation/jeton/) ? Je pose la question au regard des nouveautés API dans les comptes entreprises qui semblent datées de ce mois-ci.

**Comment by bokub** [comment]
Ah j'ignorais qu'il y avait des nouveautés datant de ce mois-ci.

Pourquoi tu n'essaies pas par toi-même ? Je suis curieux d'avoir la réponse mais je n'ai pas de compte entreprise pour tester

**Comment by wpchannel** [comment]
Disons que récemment ils ont migré les comptes si j'en crois un mail reçu il y a quelques jours et dans mon souvenir je n'avais pas accès aux API mais je peux me tromper. Je vais tenter des choses ! En tout cas merci de ton retour.

**Comment by bokub** [comment]
Ben dans tous les cas il va falloir que tu me donnes un consentement en passant par [Authorize V1](https://datahub-enedis.fr/services-api/data-connect/documentation/autorisation-v1/)

Et vu l'URL je pense qu'il faut être particulier mais je peux me tromper

![image](https://github.com/user-attachments/assets/d6a54443-4bbf-4b09-8440-399df9c09a23)
