### ISSUE TITLE
erreur sur l'url de callback

### ISSUE THREAD

**Issue by piars777** [bokub/linky#9]
Bonjour,
Tout d'abord Merci pour cet outil,
Par contre il y a un probleme sur l'url de callback . Une fois qu on s'est authentifié sur le site enedis puis on est redirigé sur le callback [https://conso.vercel.app/api?](url) avec les les parametres, on a un 404. J'étais obligé d'ajouter le mot callback à l'url pour que ça fonctionne [https://conso.vercel.app/api/callback?](url)

**Comment by bokub** [comment]
Hello,

Oui en effet j'attend que Enedis mette cette URL à jour mais il sont plutôt lents, il faut parfois attendre jusqu'à une semaine...

En attendant, j'avais mis un URL rewrite pour que `/api` appelle la route `/api/callback` mais ça s'est mal déployé. Normalement ça devrait être corrigé: [conso.vercel.app/api](https://conso.vercel.app/api)

**Comment by bokub** [comment]
C'est corrigé !
